/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.nyit.pd.pdbt;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int blue=0x7f040000;
        public static final int orange=0x7f040001;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int custom_button=0x7f020000;
        public static final int ic_launcher=0x7f020001;
    }
    public static final class id {
        public static final int action_disconnect=0x7f09001b;
        public static final int connStatus=0x7f090007;
        public static final int connectedLayout=0x7f090004;
        public static final int device_address=0x7f09001a;
        public static final int device_name=0x7f090019;
        public static final int finalPatientName=0x7f09000a;
        public static final int linearLayout=0x7f090008;
        public static final int prePatientName=0x7f090002;
        public static final int scrollView=0x7f09000b;
        public static final int startConnection=0x7f090003;
        public static final int statusIndicator=0x7f090006;
        public static final int sw_arrive_at_chair=0x7f090013;
        public static final int sw_chair_rise=0x7f090012;
        public static final int sw_freeze=0x7f09000e;
        public static final int sw_get_up_from_chair=0x7f090014;
        public static final int sw_sitting=0x7f090011;
        public static final int sw_standing=0x7f09000d;
        public static final int sw_start_sitting=0x7f090010;
        public static final int sw_turn_left=0x7f090017;
        public static final int sw_turn_right=0x7f090018;
        public static final int sw_unfreeze=0x7f09000f;
        public static final int sw_walk_forward=0x7f090016;
        public static final int sw_walking=0x7f090015;
        public static final int textView=0x7f090005;
        public static final int textView2=0x7f090001;
        public static final int textView3=0x7f090009;
        public static final int toggleGroup=0x7f09000c;
        public static final int unconnectedLayout=0x7f090000;
    }
    public static final class layout {
        public static final int activity_nyitpdbt=0x7f030000;
        public static final int listitem_device=0x7f030001;
    }
    public static final class menu {
        public static final int nyitpdbt=0x7f080000;
    }
    public static final class string {
        public static final int action_settings=0x7f060000;
        public static final int app_name=0x7f060001;
        public static final int hello_world=0x7f060002;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f070000;
    }
}
