/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.cirugias;

public final class R {
    public static final class array {
        public static final int opciones=0x7f050000;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int divisor=0x7f060000;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int AbsoluteLayout01=0x7f09002b;
        public static final int AbsoluteLayout1=0x7f090022;
        public static final int LinearLayout01=0x7f09002f;
        public static final int RelativeLayout1=0x7f09000b;
        public static final int TextView03=0x7f09002e;
        public static final int TextView04=0x7f09002d;
        public static final int TextView05=0x7f09002c;
        public static final int button1=0x7f09000f;
        public static final int button2=0x7f090012;
        public static final int button3=0x7f090016;
        public static final int button4=0x7f090017;
        public static final int editText1=0x7f09001b;
        public static final int editText2=0x7f09001d;
        public static final int editText3=0x7f09001f;
        public static final int editText4=0x7f09001a;
        public static final int editText5=0x7f090034;
        public static final int editText6=0x7f090021;
        public static final int horizontalScrollView1=0x7f090014;
        public static final int linearLayout1=0x7f090004;
        public static final int listView1=0x7f09000c;
        public static final int listView2=0x7f09000e;
        public static final int menu_settings=0x7f090035;
        public static final int np1=0x7f090030;
        public static final int np2=0x7f090031;
        public static final int np3=0x7f090032;
        public static final int np4=0x7f090027;
        public static final int np5=0x7f090028;
        public static final int np6=0x7f090029;
        public static final int paciente=0x7f090000;
        public static final int pager_title_strip=0x7f090002;
        public static final int scrollView1=0x7f090013;
        public static final int spinner1=0x7f090011;
        public static final int textView1=0x7f09000d;
        public static final int textView10=0x7f090033;
        public static final int textView11=0x7f090019;
        public static final int textView12=0x7f090020;
        public static final int textView2=0x7f09002a;
        public static final int textView3=0x7f09001e;
        public static final int textView4=0x7f090023;
        public static final int textView5=0x7f090024;
        public static final int textView6=0x7f090025;
        public static final int textView7=0x7f090026;
        public static final int textView8=0x7f090018;
        public static final int textView9=0x7f09001c;
        public static final int textosw=0x7f090015;
        public static final int texts1=0x7f090010;
        public static final int ts1=0x7f090005;
        public static final int ts10=0x7f09000a;
        public static final int ts2=0x7f090008;
        public static final int ts3=0x7f090006;
        public static final int ts4=0x7f090007;
        public static final int ts5=0x7f090009;
        public static final int tvs1=0x7f090003;
        public static final int view=0x7f090001;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int consultas=0x7f030001;
        public static final int consultas1=0x7f030002;
        public static final int listado1=0x7f030003;
        public static final int listado2=0x7f030004;
        public static final int paciente=0x7f030005;
        public static final int welcome=0x7f030006;
    }
    public static final class menu {
        public static final int activity_actividad3=0x7f080000;
        public static final int activity_listados=0x7f080001;
        public static final int activity_main=0x7f080002;
    }
    public static final class string {
        public static final int app_name=0x7f070000;
        public static final int bienvenido=0x7f070001;
        public static final int hello_world=0x7f070002;
        public static final int menu_settings=0x7f070003;
        public static final int title_activity_actividad3=0x7f070004;
        public static final int title_activity_listados=0x7f070005;
    }
    public static final class style {
        /**  API 11 theme customizations can go here. 
 API 14 theme customizations can go here. 

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f040000;
        /**  All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f040001;
    }
}
