02-16 17:29:20.413    3616-3616/br.com.ideenbox.easydoctor E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: br.com.ideenbox.easydoctor, PID: 3616
    java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.ideenbox.easydoctor/br.com.ideenbox.easydoctor.activities.OfficeDetailsActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@18ab25c9: Unmarshalling unknown type code 7471202 at offset 23700
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
     Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@18ab25c9: Unmarshalling unknown type code 7471202 at offset 23700
            at android.os.Parcel.readValue(Parcel.java:2222)
            at android.os.Parcel.readListInternal(Parcel.java:2520)
            at android.os.Parcel.readArrayList(Parcel.java:1836)
            at br.com.ideenbox.easydoctor.domain.OfficeFreeHour.<init>(OfficeFreeHour.java:37)
            at br.com.ideenbox.easydoctor.domain.OfficeFreeHour$1.createFromParcel(OfficeFreeHour.java:150)
            at br.com.ideenbox.easydoctor.domain.OfficeFreeHour$1.createFromParcel(OfficeFreeHour.java:147)
            at android.os.Parcel.readParcelable(Parcel.java:2246)
            at android.os.Parcel.readValue(Parcel.java:2146)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
            at android.os.Bundle.getParcelable(Bundle.java:804)
            at android.content.Intent.getParcelableExtra(Intent.java:4850)
            at br.com.ideenbox.easydoctor.activities.OfficeDetailsActivity.onCreate(OfficeDetailsActivity.java:62)
            at android.app.Activity.performCreate(Activity.java:5953)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)