/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.alcoapps.moduletemplate;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import java.util.HashMap;
import org.appcelerator.kroll.KrollDict;
//import org.appcelerator.titanium.util.TiConvert; // toInt, toFloat, toDouble, toBoolean, toColor


@Kroll.module(name="Moduletemplate", id="com.alcoapps.moduletemplate")
public class ModuletemplateModule extends KrollModule
{
  private String myproperty;
	
	// Standard Debugging variables
	private static final String TAG = "ModuletemplateModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public ModuletemplateModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// ################################## METHODS START HERE

	// Methods
	@Kroll.method
	public String example()
	{
		Log.d(TAG, "example called");
		return "hello world from the module";
		/*
		 * JavaScript:
		 * var x=mymod.example;
		 * x holds "hello world from the module"
		 */
	}
	
	@SuppressWarnings({ "unchecked", "rawtypes" })
	@Kroll.method
	// this example demonstrates how to receive a JavaScript Object
	public String getObj(HashMap hm){
		KrollDict args = new KrollDict(hm);
		return args.getString("value");
		/*
		 * JavaScript:
		 * console.log(myMod.getObj({
		 *    value:'Alco'
		 * }));
		 * will return "Alco"
		 */
	}
	
	// Properties
	@Kroll.getProperty @Kroll.method
	public String getExampleProp()
	{
		Log.d(TAG, "get example property");
		return myproperty;
		/*
		 * JavaScript:
		 * console.log(mymod.getExampleProp());
		 */
	}
	
	
	@Kroll.setProperty @Kroll.method
	public void setExampleProp(String value) {
		myproperty=value;
		Log.d(TAG, "set example property: " + value);
		/*
		 * JavaScript:
		 * mod.setExampleProp('myvalue');
		 */
	}

}

