/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.nicholasthompson.test;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int beer=0x7f020000;
        public static final int cooltext1704081120=0x7f020001;
        public static final int cooltext1704090630=0x7f020002;
        public static final int ic_launcher=0x7f020003;
    }
    public static final class id {
        public static final int action_settings=0x7f080009;
        public static final int button=0x7f080005;
        public static final int button2=0x7f080006;
        public static final int button4=0x7f080007;
        public static final int button6=0x7f080002;
        public static final int front=0x7f080004;
        public static final int group_button=0x7f080008;
        public static final int imageView=0x7f080001;
        public static final int imageView2=0x7f080000;
        public static final int scanButton=0x7f080003;
    }
    public static final class layout {
        public static final int activity_cab=0x7f030000;
        public static final int activity_cock=0x7f030001;
        public static final int activity_fav=0x7f030002;
        public static final int activity_group=0x7f030003;
        public static final int activity_my=0x7f030004;
    }
    public static final class menu {
        public static final int cab=0x7f070000;
        public static final int cock=0x7f070001;
        public static final int fav=0x7f070002;
        public static final int group=0x7f070003;
        public static final int my=0x7f070004;
    }
    public static final class string {
        public static final int action_settings=0x7f050000;
        public static final int app_name=0x7f050001;
        public static final int cabinet_button=0x7f050002;
        public static final int cock_button=0x7f050003;
        public static final int fav_button=0x7f050004;
        public static final int group_button=0x7f050005;
        public static final int hello_world=0x7f050006;
        public static final int scan_button=0x7f050007;
        public static final int set_button=0x7f050008;
        public static final int title_activity_cab=0x7f050009;
        public static final int title_activity_cock=0x7f05000a;
        public static final int title_activity_fav=0x7f05000b;
        public static final int title_activity_group=0x7f05000c;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f060000;
    }
}
