/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package cl.crossline.owncalendarview;

public final class R {
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int arrowLeft=0x7f010003;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int arrowRight=0x7f010002;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>monday</code></td><td>0</td><td></td></tr>
<tr><td><code>tuesday</code></td><td>1</td><td></td></tr>
<tr><td><code>wednesday</code></td><td>2</td><td></td></tr>
<tr><td><code>thursday</code></td><td>3</td><td></td></tr>
<tr><td><code>friday</code></td><td>4</td><td></td></tr>
<tr><td><code>saturday</code></td><td>5</td><td></td></tr>
<tr><td><code>sunday</code></td><td>6</td><td></td></tr>
</table>
         */
        public static final int firstDay=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int image=0x7f010001;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int isSeparatedView=0x7f010007;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int monthFontSize=0x7f010006;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int numberFontSize=0x7f010005;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int shownLines=0x7f010008;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int titleFontSize=0x7f010004;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int arrow_left=0x7f020000;
        public static final int arrow_rigth=0x7f020001;
        public static final int ic_launcher=0x7f020002;
    }
    public static final class id {
        public static final int action_settings=0x7f040008;
        public static final int friday=0x7f040004;
        public static final int monday=0x7f040000;
        public static final int ownCalendar=0x7f040007;
        public static final int saturday=0x7f040005;
        public static final int sunday=0x7f040006;
        public static final int thursday=0x7f040003;
        public static final int tuesday=0x7f040001;
        public static final int wednesday=0x7f040002;
    }
    public static final class layout {
        public static final int activity_my=0x7f030000;
    }
    public static final class menu {
        public static final int my=0x7f080000;
    }
    public static final class string {
        public static final int action_settings=0x7f060000;
        public static final int app_name=0x7f060001;
        public static final int hello_world=0x7f060002;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f070000;
    }
    public static final class styleable {
        /** Attributes that can be used with a CustomCalendar.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CustomCalendar_arrowLeft cl.crossline.owncalendarview:arrowLeft}</code></td><td></td></tr>
           <tr><td><code>{@link #CustomCalendar_arrowRight cl.crossline.owncalendarview:arrowRight}</code></td><td></td></tr>
           <tr><td><code>{@link #CustomCalendar_firstDay cl.crossline.owncalendarview:firstDay}</code></td><td></td></tr>
           <tr><td><code>{@link #CustomCalendar_image cl.crossline.owncalendarview:image}</code></td><td></td></tr>
           <tr><td><code>{@link #CustomCalendar_isSeparatedView cl.crossline.owncalendarview:isSeparatedView}</code></td><td></td></tr>
           <tr><td><code>{@link #CustomCalendar_monthFontSize cl.crossline.owncalendarview:monthFontSize}</code></td><td></td></tr>
           <tr><td><code>{@link #CustomCalendar_numberFontSize cl.crossline.owncalendarview:numberFontSize}</code></td><td></td></tr>
           <tr><td><code>{@link #CustomCalendar_shownLines cl.crossline.owncalendarview:shownLines}</code></td><td></td></tr>
           <tr><td><code>{@link #CustomCalendar_titleFontSize cl.crossline.owncalendarview:titleFontSize}</code></td><td></td></tr>
           </table>
           @see #CustomCalendar_arrowLeft
           @see #CustomCalendar_arrowRight
           @see #CustomCalendar_firstDay
           @see #CustomCalendar_image
           @see #CustomCalendar_isSeparatedView
           @see #CustomCalendar_monthFontSize
           @see #CustomCalendar_numberFontSize
           @see #CustomCalendar_shownLines
           @see #CustomCalendar_titleFontSize
         */
        public static final int[] CustomCalendar = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008
        };
        /**
          <p>This symbol is the offset where the {@link cl.crossline.owncalendarview.R.attr#arrowLeft}
          attribute's value can be found in the {@link #CustomCalendar} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name cl.crossline.owncalendarview:arrowLeft
        */
        public static final int CustomCalendar_arrowLeft = 3;
        /**
          <p>This symbol is the offset where the {@link cl.crossline.owncalendarview.R.attr#arrowRight}
          attribute's value can be found in the {@link #CustomCalendar} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name cl.crossline.owncalendarview:arrowRight
        */
        public static final int CustomCalendar_arrowRight = 2;
        /**
          <p>This symbol is the offset where the {@link cl.crossline.owncalendarview.R.attr#firstDay}
          attribute's value can be found in the {@link #CustomCalendar} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>monday</code></td><td>0</td><td></td></tr>
<tr><td><code>tuesday</code></td><td>1</td><td></td></tr>
<tr><td><code>wednesday</code></td><td>2</td><td></td></tr>
<tr><td><code>thursday</code></td><td>3</td><td></td></tr>
<tr><td><code>friday</code></td><td>4</td><td></td></tr>
<tr><td><code>saturday</code></td><td>5</td><td></td></tr>
<tr><td><code>sunday</code></td><td>6</td><td></td></tr>
</table>
          @attr name cl.crossline.owncalendarview:firstDay
        */
        public static final int CustomCalendar_firstDay = 0;
        /**
          <p>This symbol is the offset where the {@link cl.crossline.owncalendarview.R.attr#image}
          attribute's value can be found in the {@link #CustomCalendar} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name cl.crossline.owncalendarview:image
        */
        public static final int CustomCalendar_image = 1;
        /**
          <p>This symbol is the offset where the {@link cl.crossline.owncalendarview.R.attr#isSeparatedView}
          attribute's value can be found in the {@link #CustomCalendar} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name cl.crossline.owncalendarview:isSeparatedView
        */
        public static final int CustomCalendar_isSeparatedView = 7;
        /**
          <p>This symbol is the offset where the {@link cl.crossline.owncalendarview.R.attr#monthFontSize}
          attribute's value can be found in the {@link #CustomCalendar} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name cl.crossline.owncalendarview:monthFontSize
        */
        public static final int CustomCalendar_monthFontSize = 6;
        /**
          <p>This symbol is the offset where the {@link cl.crossline.owncalendarview.R.attr#numberFontSize}
          attribute's value can be found in the {@link #CustomCalendar} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name cl.crossline.owncalendarview:numberFontSize
        */
        public static final int CustomCalendar_numberFontSize = 5;
        /**
          <p>This symbol is the offset where the {@link cl.crossline.owncalendarview.R.attr#shownLines}
          attribute's value can be found in the {@link #CustomCalendar} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name cl.crossline.owncalendarview:shownLines
        */
        public static final int CustomCalendar_shownLines = 8;
        /**
          <p>This symbol is the offset where the {@link cl.crossline.owncalendarview.R.attr#titleFontSize}
          attribute's value can be found in the {@link #CustomCalendar} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name cl.crossline.owncalendarview:titleFontSize
        */
        public static final int CustomCalendar_titleFontSize = 4;
    };
}
