/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.sygic;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;

import android.content.Intent;
import android.view.SurfaceView;

import com.sygic.ApplicationApi.ApplicationAPI;
import com.sygic.ApplicationApi.LONGPOSITION;
import com.sygic.ApplicationApi.SError;
import com.sygic.ApplicationApi.SStopOffPoint;
import com.sygic.ApplicationApi.SStopOffPointArray;

@Kroll.module(name = "Sygic", id = "ti.sygic")
public class SygicModule extends KrollModule {

	private static final String LCAT = "SygicModule";
	private SError Error = new SError();

	private String strItineraryName = "abc";

	public SygicModule() {
		super();
	}

	@Kroll.method
	public void launchNavigationActivity(TiViewProxy view, Float lat, Float lon) {
		// Set the static parent module as this, so that the navigation activity can fire events on its own.
		NavigationActivity.setParentModule(this);
		NavigationActivity.setView(view);
		NavigationActivity.setDestination(lat, lon);

		Log("Creating intent for navigation activity");
		Intent intent = new Intent(getActivity(),NavigationActivity.class);
		Log("Starting navigation activity");
		getActivity().startActivity(intent); 
	}

	@Kroll.method
	public void stopNavigation() {
		ApplicationAPI.StopNavigation(Error, 0);
	}

	@Kroll.setProperty
	@Kroll.method
	public void setRoute(String address) {
		Log("Setting module destination address to: " + address);
		// TODO: route there!
	}

	@Kroll.getProperty
	@Kroll.method
	public String getDestinationAddress() {
		return "";
	}

	@Kroll.method
	public void navigateTo(String address) {
		Log("Setting module destination address to: " + address);

		LONGPOSITION location = new LONGPOSITION();
		ApplicationAPI.LocationFromAddress(Error, location, address, false, true, 0);

		SStopOffPointArray PointArr = new SStopOffPointArray();
		PointArr.add(new SStopOffPoint(false, false, 3, location.lX, location.lY, 0, null, "wp_" + 0, null));

		ApplicationAPI.DeleteItinerary(Error, strItineraryName, 0);
		ApplicationAPI.AddItinerary(Error, PointArr, 1, strItineraryName, 0);

		new Thread(new Runnable() {
			@Override
			public void run() {
				ApplicationAPI.SetRoute(Error, strItineraryName, 0, false, 0);
			}
		}).start();
	}
	
	private static void Log(String message)
	{
		org.appcelerator.kroll.common.Log.i(LCAT, message);
		android.util.Log.i(LCAT, message);
	}
}