/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package br.com.ohexpress.ohex;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
    }
    public static final class drawable {
        public static final int ic_email=0x7f020000;
        public static final int ic_nome=0x7f020001;
        public static final int ic_senha=0x7f020002;
        public static final int ic_useracc=0x7f020003;
    }
    public static final class id {
        public static final int action_settings=0x7f090007;
        public static final int action_settings2=0x7f090008;
        public static final int action_settings3=0x7f090009;
        public static final int button=0x7f090006;
        public static final int textView=0x7f090000;
        public static final int textView2=0x7f090001;
        public static final int tvEmail=0x7f090004;
        public static final int tvLogin=0x7f090003;
        public static final int tvNome=0x7f090002;
        public static final int tvSenha=0x7f090005;
    }
    public static final class layout {
        public static final int activity_main=0x7f040000;
    }
    public static final class menu {
        public static final int menu_main=0x7f080000;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f030000;
    }
    public static final class string {
        public static final int action_settings=0x7f070000;
        public static final int action_settings2=0x7f070001;
        public static final int action_settings3=0x7f070002;
        public static final int action_settings4=0x7f070003;
        public static final int app_name=0x7f070004;
        public static final int hello_world=0x7f070005;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f050000;
        public static final int MyActionBarTheme=0x7f050001;
        public static final int MyCustomTheme=0x7f050002;
    }
}
