/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.joona.movies;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class id {
        public static final int action_settings=0x7f08000e;
        public static final int actors_textview=0x7f080007;
        public static final int director_textview=0x7f080008;
        public static final int genres_textview=0x7f080009;
        public static final int imdb_link_textview=0x7f08000a;
        public static final int internal_movies_checkbox=0x7f08000c;
        public static final int lower_listfragment_textview=0x7f080002;
        public static final int lower_main_frame=0x7f080001;
        public static final int movie_image_webview=0x7f080005;
        public static final int movie_name_edittext=0x7f08000b;
        public static final int movie_year_textview=0x7f080006;
        public static final int movies_listview=0x7f080003;
        public static final int search_movie_button=0x7f08000d;
        public static final int title_textview=0x7f080004;
        public static final int upper_main_frame=0x7f080000;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int fragment_lower=0x7f030001;
        public static final int fragment_lower_list=0x7f030002;
        public static final int fragment_lower_movie_definition=0x7f030003;
        public static final int fragment_upper=0x7f030004;
    }
    public static final class menu {
        public static final int menu_main=0x7f070000;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class string {
        public static final int action_settings=0x7f060000;
        public static final int actors=0x7f060001;
        public static final int app_name=0x7f060002;
        public static final int director=0x7f060003;
        public static final int genres=0x7f060004;
        public static final int hello_blank_fragment=0x7f060005;
        public static final int hello_world=0x7f060006;
        public static final int movie_name=0x7f060007;
        public static final int search=0x7f060008;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f040000;
    }
}
