/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ortiz.sangredeportiva;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int fix=0x7f020000;
        public static final int goleadores=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int posiciones=0x7f020003;
    }
    public static final class id {
        public static final int alerta_partidos=0x7f060003;
        public static final int alerta_tabla=0x7f060004;
        public static final int bt_calendario=0x7f060000;
        public static final int bt_goleadores=0x7f060002;
        public static final int bt_posiciones=0x7f060001;
        public static final int equipo_l=0x7f06001c;
        public static final int equipo_v=0x7f060022;
        public static final int fecha_date=0x7f06001f;
        public static final int head_goles=0x7f06000f;
        public static final int head_nombre=0x7f06000d;
        public static final int header_draws=0x7f060029;
        public static final int header_goles=0x7f060025;
        public static final int header_losses=0x7f06002a;
        public static final int header_nombregoleador=0x7f060024;
        public static final int header_points=0x7f060027;
        public static final int header_pos=0x7f060026;
        public static final int header_team=0x7f060015;
        public static final int header_wins=0x7f060028;
        public static final int jugado=0x7f060020;
        public static final int lineaDosEquipo=0x7f060021;
        public static final int lineaIntermediaFixture=0x7f06001e;
        public static final int lineaUnoEquipo=0x7f060007;
        public static final int list=0x7f060008;
        public static final int list_fixt=0x7f06000b;
        public static final int list_goles=0x7f060011;
        public static final int list_pos=0x7f06001b;
        public static final int local_principal=0x7f06002b;
        public static final int return_activity=0x7f06002e;
        public static final int score_l=0x7f06001d;
        public static final int score_v=0x7f060023;
        public static final int tablaFixture=0x7f060009;
        public static final int tablaFixture_principal=0x7f060005;
        public static final int tabla_draws=0x7f060017;
        public static final int tabla_ga=0x7f06001a;
        public static final int tabla_gf=0x7f060019;
        public static final int tabla_goles=0x7f060010;
        public static final int tabla_lost=0x7f060018;
        public static final int tabla_nombre_goleador=0x7f06000e;
        public static final int tabla_points=0x7f060014;
        public static final int tabla_pos=0x7f060012;
        public static final int tabla_team=0x7f060013;
        public static final int tabla_wins=0x7f060016;
        public static final int title_positions=0x7f06000c;
        public static final int tv_fixture=0x7f06000a;
        public static final int tv_fixture_principal=0x7f060006;
        public static final int visitante_principal=0x7f06002d;
        public static final int vs=0x7f06002c;
    }
    public static final class layout {
        public static final int activity_principal=0x7f030000;
        public static final int lis_fixr=0x7f030001;
        public static final int list_goleadores=0x7f030002;
        public static final int list_posiciones=0x7f030003;
        public static final int tabla_fixt=0x7f030004;
        public static final int tabla_goleadores=0x7f030005;
        public static final int tabla_posic=0x7f030006;
        public static final int tabla_principal=0x7f030007;
    }
    public static final class menu {
        public static final int menu=0x7f050000;
    }
    public static final class string {
        public static final int alerta_partidos=0x7f040010;
        public static final int app_name=0x7f040000;
        public static final int bt_estadisticas=0x7f040013;
        public static final int bt_fixture=0x7f040009;
        public static final int bt_goleadores=0x7f040011;
        public static final int bt_posiciones=0x7f04000b;
        public static final int header_draws=0x7f040005;
        public static final int header_ga=0x7f040007;
        public static final int header_gf=0x7f040008;
        public static final int header_goles=0x7f04000f;
        public static final int header_losses=0x7f040006;
        public static final int header_nombregoleador=0x7f04000e;
        public static final int header_points=0x7f040001;
        public static final int header_pos=0x7f04000a;
        public static final int header_team=0x7f040003;
        public static final int header_wins=0x7f040004;
        public static final int partidos_al_dia=0x7f04000c;
        public static final int titulo_fixture=0x7f040002;
        public static final int titulo_goleadores=0x7f04000d;
        public static final int titulo_posiciones=0x7f040012;
    }
}
