/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.xubin.clickproject;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int action_settings=0x7f08000f;
        public static final int add=0x7f080007;
        public static final int btn=0x7f080001;
        public static final int change=0x7f08000c;
        public static final int check=0x7f08000e;
        public static final int div=0x7f08000a;
        public static final int end=0x7f080006;
        public static final int img=0x7f08000b;
        public static final int min=0x7f080008;
        public static final int myedit=0x7f080000;
        public static final int num1=0x7f080003;
        public static final int num2=0x7f080005;
        public static final int password=0x7f08000d;
        public static final int sub=0x7f080009;
        public static final int tv=0x7f080004;
        public static final int txt=0x7f080002;
    }
    public static final class layout {
        public static final int activity_my=0x7f030000;
    }
    public static final class menu {
        public static final int my=0x7f070000;
    }
    public static final class string {
        public static final int action_settings=0x7f050000;
        public static final int app_name=0x7f050001;
        public static final int hello_world=0x7f050002;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f060000;
    }
}
