/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.xubin.myapplication;

public final class R {
    public static final class array {
        public static final int city_labels=0x7f040000;
        public static final int color_labels=0x7f040001;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int action_settings=0x7f090012;
        public static final int button=0x7f090010;
        public static final int button1=0x7f090011;
        public static final int check=0x7f09000a;
        public static final int check1=0x7f09000b;
        public static final int check2=0x7f09000c;
        public static final int dp=0x7f090003;
        public static final int edit=0x7f090001;
        public static final int edit1=0x7f090002;
        public static final int encoding=0x7f090007;
        public static final int ib=0x7f090006;
        public static final int image=0x7f090005;
        public static final int mycolor=0x7f09000e;
        public static final int myedu=0x7f09000f;
        public static final int radio=0x7f090008;
        public static final int radio1=0x7f090009;
        public static final int spinner=0x7f09000d;
        public static final int text=0x7f090000;
        public static final int tp=0x7f090004;
    }
    public static final class layout {
        public static final int activity_my=0x7f030000;
    }
    public static final class menu {
        public static final int my=0x7f080000;
    }
    public static final class string {
        public static final int action_settings=0x7f060000;
        public static final int app_name=0x7f060001;
        public static final int city_prompt=0x7f060002;
        public static final int color_prompt=0x7f060003;
        public static final int hello_world=0x7f060004;
    }
    public static final class style {
        public static final int mytext=0x7f070000;
    }
}
