/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package bpst.met.imagelisttest;

public final class R {
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int columnCount=0x7f010000;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int column_count=0x7f010002;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int column_count_landscape=0x7f010004;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int column_count_portrait=0x7f010003;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int grid_paddingBottom=0x7f010009;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int grid_paddingLeft=0x7f010006;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int grid_paddingRight=0x7f010007;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int grid_paddingTop=0x7f010008;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int item_margin=0x7f010005;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int mode=0x7f010001;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
        public static final int reset_button=0x7f020001;
    }
    public static final class id {
        public static final int action_settings=0x7f080004;
        public static final int grid=0x7f080000;
        public static final int imgView=0x7f080003;
        public static final int refresh=0x7f080002;
        public static final int reset_back=0x7f080001;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int image_element=0x7f030001;
    }
    public static final class menu {
        public static final int menu_main=0x7f070000;
    }
    public static final class string {
        public static final int action_settings=0x7f050000;
        public static final int app_name=0x7f050001;
        public static final int hello_world=0x7f050002;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f060000;
    }
    public static final class styleable {
        /** Attributes that can be used with a MyGrid.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MyGrid_columnCount bpst.met.imagelisttest:columnCount}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGrid_mode bpst.met.imagelisttest:mode}</code></td><td></td></tr>
           </table>
           @see #MyGrid_columnCount
           @see #MyGrid_mode
         */
        public static final int[] MyGrid = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link bpst.met.imagelisttest.R.attr#columnCount}
          attribute's value can be found in the {@link #MyGrid} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name bpst.met.imagelisttest:columnCount
        */
        public static final int MyGrid_columnCount = 0;
        /**
          <p>This symbol is the offset where the {@link bpst.met.imagelisttest.R.attr#mode}
          attribute's value can be found in the {@link #MyGrid} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name bpst.met.imagelisttest:mode
        */
        public static final int MyGrid_mode = 1;
        /** Attributes that can be used with a StaggeredGridView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #StaggeredGridView_column_count bpst.met.imagelisttest:column_count}</code></td><td></td></tr>
           <tr><td><code>{@link #StaggeredGridView_column_count_landscape bpst.met.imagelisttest:column_count_landscape}</code></td><td></td></tr>
           <tr><td><code>{@link #StaggeredGridView_column_count_portrait bpst.met.imagelisttest:column_count_portrait}</code></td><td></td></tr>
           <tr><td><code>{@link #StaggeredGridView_grid_paddingBottom bpst.met.imagelisttest:grid_paddingBottom}</code></td><td></td></tr>
           <tr><td><code>{@link #StaggeredGridView_grid_paddingLeft bpst.met.imagelisttest:grid_paddingLeft}</code></td><td></td></tr>
           <tr><td><code>{@link #StaggeredGridView_grid_paddingRight bpst.met.imagelisttest:grid_paddingRight}</code></td><td></td></tr>
           <tr><td><code>{@link #StaggeredGridView_grid_paddingTop bpst.met.imagelisttest:grid_paddingTop}</code></td><td></td></tr>
           <tr><td><code>{@link #StaggeredGridView_item_margin bpst.met.imagelisttest:item_margin}</code></td><td></td></tr>
           </table>
           @see #StaggeredGridView_column_count
           @see #StaggeredGridView_column_count_landscape
           @see #StaggeredGridView_column_count_portrait
           @see #StaggeredGridView_grid_paddingBottom
           @see #StaggeredGridView_grid_paddingLeft
           @see #StaggeredGridView_grid_paddingRight
           @see #StaggeredGridView_grid_paddingTop
           @see #StaggeredGridView_item_margin
         */
        public static final int[] StaggeredGridView = {
            0x7f010002, 0x7f010003, 0x7f010004, 0x7f010005,
            0x7f010006, 0x7f010007, 0x7f010008, 0x7f010009
        };
        /**
          <p>This symbol is the offset where the {@link bpst.met.imagelisttest.R.attr#column_count}
          attribute's value can be found in the {@link #StaggeredGridView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name bpst.met.imagelisttest:column_count
        */
        public static final int StaggeredGridView_column_count = 0;
        /**
          <p>This symbol is the offset where the {@link bpst.met.imagelisttest.R.attr#column_count_landscape}
          attribute's value can be found in the {@link #StaggeredGridView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name bpst.met.imagelisttest:column_count_landscape
        */
        public static final int StaggeredGridView_column_count_landscape = 2;
        /**
          <p>This symbol is the offset where the {@link bpst.met.imagelisttest.R.attr#column_count_portrait}
          attribute's value can be found in the {@link #StaggeredGridView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name bpst.met.imagelisttest:column_count_portrait
        */
        public static final int StaggeredGridView_column_count_portrait = 1;
        /**
          <p>This symbol is the offset where the {@link bpst.met.imagelisttest.R.attr#grid_paddingBottom}
          attribute's value can be found in the {@link #StaggeredGridView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name bpst.met.imagelisttest:grid_paddingBottom
        */
        public static final int StaggeredGridView_grid_paddingBottom = 7;
        /**
          <p>This symbol is the offset where the {@link bpst.met.imagelisttest.R.attr#grid_paddingLeft}
          attribute's value can be found in the {@link #StaggeredGridView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name bpst.met.imagelisttest:grid_paddingLeft
        */
        public static final int StaggeredGridView_grid_paddingLeft = 4;
        /**
          <p>This symbol is the offset where the {@link bpst.met.imagelisttest.R.attr#grid_paddingRight}
          attribute's value can be found in the {@link #StaggeredGridView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name bpst.met.imagelisttest:grid_paddingRight
        */
        public static final int StaggeredGridView_grid_paddingRight = 5;
        /**
          <p>This symbol is the offset where the {@link bpst.met.imagelisttest.R.attr#grid_paddingTop}
          attribute's value can be found in the {@link #StaggeredGridView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name bpst.met.imagelisttest:grid_paddingTop
        */
        public static final int StaggeredGridView_grid_paddingTop = 6;
        /**
          <p>This symbol is the offset where the {@link bpst.met.imagelisttest.R.attr#item_margin}
          attribute's value can be found in the {@link #StaggeredGridView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name bpst.met.imagelisttest:item_margin
        */
        public static final int StaggeredGridView_item_margin = 3;
    };
}
