/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.miguel.hechos_curiosos;

public final class R {
    public static final class array {
        public static final int color=0x7f040000;
        public static final int frases=0x7f040001;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int HechoCuriosoTextView=0x7f090003;
        public static final int RelativeMain=0x7f090000;
        public static final int action_settings=0x7f090004;
        public static final int ask=0x7f090001;
        public static final int button=0x7f090002;
    }
    public static final class layout {
        public static final int activity_hechos_curiosos=0x7f030000;
    }
    public static final class menu {
        public static final int hechos_curiosos=0x7f080000;
    }
    public static final class string {
        public static final int ChangeButton=0x7f060000;
        public static final int HechoCuriosoTextView=0x7f060001;
        public static final int action_settings=0x7f060002;
        public static final int app_name=0x7f060003;
        public static final int ask=0x7f060004;
        public static final int hello_world=0x7f060005;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f070000;
    }
}
