/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.team.customui;

public final class R {
    public static final class attr {
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int imageAlpha=0x7f010000;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int imageAspectRatio=0x7f010001;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int imagePaddingBottom=0x7f010002;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int imagePaddingLeft=0x7f010003;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int imagePaddingRight=0x7f010004;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int imagePaddingTop=0x7f010005;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>fillXY</code></td><td>0</td><td></td></tr>
<tr><td><code>center</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int imageScaleType=0x7f010006;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int imageSrc=0x7f010007;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int xMessage=0x7f010008;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int apple_itunes=0x7f020000;
        public static final int clef=0x7f020001;
        public static final int i_explorer=0x7f020002;
        public static final int ic_launcher=0x7f020003;
        public static final int win_media=0x7f020004;
    }
    public static final class id {
        public static final int MyCustomView=0x7f040009;
        public static final int action_settings=0x7f04000c;
        public static final int center=0x7f040001;
        public static final int fillXY=0x7f040000;
        public static final int myCustomView1=0x7f040002;
        public static final int myCustomView2=0x7f040003;
        public static final int myCustomView3=0x7f040005;
        public static final int myCustomView4=0x7f040006;
        public static final int myCustomView5=0x7f040007;
        public static final int myCustomView6=0x7f040008;
        public static final int myTimeView1=0x7f040004;
        public static final int textViewDate=0x7f04000a;
        public static final int textViewTime=0x7f04000b;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int sample_my_custom_view=0x7f030001;
        public static final int sample_my_time_view=0x7f030002;
    }
    public static final class menu {
        public static final int menu_main=0x7f080000;
    }
    public static final class string {
        public static final int action_settings=0x7f060000;
        public static final int app_name=0x7f060001;
        public static final int hello_world=0x7f060002;
        public static final int title_activity_main=0x7f060003;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f070000;
    }
    public static final class styleable {
        /** Attributes that can be used with a MyCustomView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MyCustomView_imageAlpha com.team.customui:imageAlpha}</code></td><td></td></tr>
           <tr><td><code>{@link #MyCustomView_imageAspectRatio com.team.customui:imageAspectRatio}</code></td><td></td></tr>
           <tr><td><code>{@link #MyCustomView_imagePaddingBottom com.team.customui:imagePaddingBottom}</code></td><td></td></tr>
           <tr><td><code>{@link #MyCustomView_imagePaddingLeft com.team.customui:imagePaddingLeft}</code></td><td></td></tr>
           <tr><td><code>{@link #MyCustomView_imagePaddingRight com.team.customui:imagePaddingRight}</code></td><td></td></tr>
           <tr><td><code>{@link #MyCustomView_imagePaddingTop com.team.customui:imagePaddingTop}</code></td><td></td></tr>
           <tr><td><code>{@link #MyCustomView_imageScaleType com.team.customui:imageScaleType}</code></td><td></td></tr>
           <tr><td><code>{@link #MyCustomView_imageSrc com.team.customui:imageSrc}</code></td><td></td></tr>
           <tr><td><code>{@link #MyCustomView_xMessage com.team.customui:xMessage}</code></td><td></td></tr>
           </table>
           @see #MyCustomView_imageAlpha
           @see #MyCustomView_imageAspectRatio
           @see #MyCustomView_imagePaddingBottom
           @see #MyCustomView_imagePaddingLeft
           @see #MyCustomView_imagePaddingRight
           @see #MyCustomView_imagePaddingTop
           @see #MyCustomView_imageScaleType
           @see #MyCustomView_imageSrc
           @see #MyCustomView_xMessage
         */
        public static final int[] MyCustomView = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008
        };
        /**
          <p>This symbol is the offset where the {@link com.team.customui.R.attr#imageAlpha}
          attribute's value can be found in the {@link #MyCustomView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.team.customui:imageAlpha
        */
        public static final int MyCustomView_imageAlpha = 0;
        /**
          <p>This symbol is the offset where the {@link com.team.customui.R.attr#imageAspectRatio}
          attribute's value can be found in the {@link #MyCustomView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.team.customui:imageAspectRatio
        */
        public static final int MyCustomView_imageAspectRatio = 1;
        /**
          <p>This symbol is the offset where the {@link com.team.customui.R.attr#imagePaddingBottom}
          attribute's value can be found in the {@link #MyCustomView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.team.customui:imagePaddingBottom
        */
        public static final int MyCustomView_imagePaddingBottom = 2;
        /**
          <p>This symbol is the offset where the {@link com.team.customui.R.attr#imagePaddingLeft}
          attribute's value can be found in the {@link #MyCustomView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.team.customui:imagePaddingLeft
        */
        public static final int MyCustomView_imagePaddingLeft = 3;
        /**
          <p>This symbol is the offset where the {@link com.team.customui.R.attr#imagePaddingRight}
          attribute's value can be found in the {@link #MyCustomView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.team.customui:imagePaddingRight
        */
        public static final int MyCustomView_imagePaddingRight = 4;
        /**
          <p>This symbol is the offset where the {@link com.team.customui.R.attr#imagePaddingTop}
          attribute's value can be found in the {@link #MyCustomView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.team.customui:imagePaddingTop
        */
        public static final int MyCustomView_imagePaddingTop = 5;
        /**
          <p>This symbol is the offset where the {@link com.team.customui.R.attr#imageScaleType}
          attribute's value can be found in the {@link #MyCustomView} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>fillXY</code></td><td>0</td><td></td></tr>
<tr><td><code>center</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.team.customui:imageScaleType
        */
        public static final int MyCustomView_imageScaleType = 6;
        /**
          <p>This symbol is the offset where the {@link com.team.customui.R.attr#imageSrc}
          attribute's value can be found in the {@link #MyCustomView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.team.customui:imageSrc
        */
        public static final int MyCustomView_imageSrc = 7;
        /**
          <p>This symbol is the offset where the {@link com.team.customui.R.attr#xMessage}
          attribute's value can be found in the {@link #MyCustomView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.team.customui:xMessage
        */
        public static final int MyCustomView_xMessage = 8;
    };
}
