/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.zhangxingyu.myapplication;

public final class R {
    public static final class attr {
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int actionSheetBackground=0x7f010000;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
         */
        public static final int actionSheetPadding=0x7f010008;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int actionSheetStyle=0x7f01000c;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
         */
        public static final int actionSheetTextSize=0x7f01000b;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int button_type=0x7f01001d;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int cancelButtonBackground=0x7f010001;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
         */
        public static final int cancelButtonMarginTop=0x7f01000a;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int cancelButtonTextColor=0x7f010006;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int otherButtonBottomBackground=0x7f010004;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int otherButtonMiddleBackground=0x7f010003;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int otherButtonSingleBackground=0x7f010005;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
         */
        public static final int otherButtonSpacing=0x7f010009;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int otherButtonTextColor=0x7f010007;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int otherButtonTopBackground=0x7f010002;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pstsDividerColor=0x7f01000f;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pstsDividerPadding=0x7f010012;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pstsIndicatorColor=0x7f01000d;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pstsIndicatorHeight=0x7f010010;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pstsScrollOffset=0x7f010014;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pstsShouldExpand=0x7f010016;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int pstsTabBackground=0x7f010015;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pstsTabPaddingLeftRight=0x7f010013;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pstsTextAllCaps=0x7f010017;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pstsUnderlineColor=0x7f01000e;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pstsUnderlineHeight=0x7f010011;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int right_image=0x7f01001e;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int right_width=0x7f01001f;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int selectedTabTextColor=0x7f010018;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int stgDividerColor=0x7f010019;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int stgDividerWidth=0x7f01001b;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int stgRadius=0x7f01001c;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int stgSelectedTabTextColor=0x7f01001a;
    }
    public static final class color {
        public static final int aliceblue=0x7f040000;
        public static final int antiquewhite=0x7f040001;
        public static final int aqua=0x7f040002;
        public static final int aquamarine=0x7f040003;
        public static final int azure=0x7f040004;
        public static final int background_tab_pressed=0x7f040005;
        public static final int beige=0x7f040006;
        public static final int bisque=0x7f040007;
        public static final int black=0x7f040008;
        public static final int blanchedalmond=0x7f040009;
        public static final int blue=0x7f04000a;
        public static final int blueviolet=0x7f04000b;
        public static final int blur_bg=0x7f04000c;
        public static final int brown=0x7f04000d;
        public static final int burlywood=0x7f04000e;
        public static final int cadetblue=0x7f04000f;
        public static final int chartreuse=0x7f040010;
        public static final int chocolate=0x7f040011;
        public static final int coral=0x7f040012;
        public static final int cornflowerblue=0x7f040013;
        public static final int cornsilk=0x7f040014;
        public static final int crimson=0x7f040015;
        public static final int cyan=0x7f040016;
        public static final int darkblue=0x7f040017;
        public static final int darkcyan=0x7f040018;
        public static final int darkgoldenrod=0x7f040019;
        public static final int darkgray=0x7f04001a;
        public static final int darkgreen=0x7f04001b;
        public static final int darkgrey=0x7f04001c;
        public static final int darkkhaki=0x7f04001d;
        public static final int darkmagenta=0x7f04001e;
        public static final int darkolivegreen=0x7f04001f;
        public static final int darkorange=0x7f040020;
        public static final int darkorchid=0x7f040021;
        public static final int darkred=0x7f040022;
        public static final int darksalmon=0x7f040023;
        public static final int darkseagreen=0x7f040024;
        public static final int darkslateblue=0x7f040025;
        public static final int darkslategray=0x7f040026;
        public static final int darkslategrey=0x7f040027;
        public static final int darkturquoise=0x7f040028;
        public static final int darkviolet=0x7f040029;
        public static final int deeppink=0x7f04002a;
        public static final int deepskyblue=0x7f04002b;
        public static final int dialog_button_focused=0x7f04002c;
        public static final int dialog_button_focused_dark=0x7f04002d;
        public static final int dialog_button_normal=0x7f04002e;
        public static final int dialog_button_normal_dark=0x7f04002f;
        public static final int dialog_button_pressed=0x7f040030;
        public static final int dialog_button_pressed_dark=0x7f040031;
        public static final int dialog_button_separator=0x7f040032;
        public static final int dialog_button_separator_dark=0x7f040033;
        public static final int dialog_button_text=0x7f040034;
        public static final int dialog_button_text_dark=0x7f040035;
        public static final int dialog_message_text=0x7f040036;
        public static final int dialog_message_text_dark=0x7f040037;
        public static final int dialog_title_separator=0x7f040038;
        public static final int dialog_title_separator_dark=0x7f040039;
        public static final int dialog_title_text=0x7f04003a;
        public static final int dialog_title_text_dark=0x7f04003b;
        public static final int dimgray=0x7f04003c;
        public static final int dimgrey=0x7f04003d;
        public static final int dodgerblue=0x7f04003e;
        public static final int firebrick=0x7f04003f;
        public static final int floralwhite=0x7f040040;
        public static final int forestgreen=0x7f040041;
        public static final int fuchsia=0x7f040042;
        public static final int gainsboro=0x7f040043;
        public static final int ghostwhite=0x7f040044;
        public static final int gold=0x7f040045;
        public static final int goldenrod=0x7f040046;
        public static final int gray=0x7f040047;
        public static final int green=0x7f040048;
        public static final int greenyellow=0x7f040049;
        public static final int honeydew=0x7f04004a;
        public static final int hotpink=0x7f04004b;
        public static final int indianred=0x7f04004c;
        public static final int indigo=0x7f04004d;
        public static final int ivory=0x7f04004e;
        public static final int khaki=0x7f04004f;
        public static final int lavender=0x7f040050;
        public static final int lavenderblush=0x7f040051;
        public static final int lawngreen=0x7f040052;
        public static final int lemonchiffon=0x7f040053;
        public static final int lightblue=0x7f040054;
        public static final int lightcoral=0x7f040055;
        public static final int lightcyan=0x7f040056;
        public static final int lightgoldenrodyellow=0x7f040057;
        public static final int lightgray=0x7f040058;
        public static final int lightgreen=0x7f040059;
        public static final int lightpink=0x7f04005a;
        public static final int lightsalmon=0x7f04005b;
        public static final int lightseagreen=0x7f04005c;
        public static final int lightskyblue=0x7f04005d;
        public static final int lightslategray=0x7f04005e;
        public static final int lightslategrey=0x7f04005f;
        public static final int lightsteelblue=0x7f040060;
        public static final int lightyellow=0x7f040061;
        public static final int lime=0x7f040062;
        public static final int limegreen=0x7f040063;
        public static final int linen=0x7f040064;
        public static final int magenta=0x7f040065;
        public static final int maroon=0x7f040066;
        public static final int mediumaquamarine=0x7f040067;
        public static final int mediumblue=0x7f040068;
        public static final int mediumorchid=0x7f040069;
        public static final int mediumpurple=0x7f04006a;
        public static final int mediumseagreen=0x7f04006b;
        public static final int mediumslateblue=0x7f04006c;
        public static final int mediumspringgreen=0x7f04006d;
        public static final int mediumturquoise=0x7f04006e;
        public static final int mediumvioletred=0x7f04006f;
        public static final int midnightblue=0x7f040070;
        public static final int mintcream=0x7f040071;
        public static final int mistyrose=0x7f040072;
        public static final int moccasin=0x7f040073;
        public static final int navajowhite=0x7f040074;
        public static final int navy=0x7f040075;
        public static final int oldlace=0x7f040076;
        public static final int olive=0x7f040077;
        public static final int olivedrab=0x7f040078;
        public static final int orange=0x7f040079;
        public static final int orangered=0x7f04007a;
        public static final int orchid=0x7f04007b;
        public static final int palegoldenrod=0x7f04007c;
        public static final int palegreen=0x7f04007d;
        public static final int paleturquoise=0x7f04007e;
        public static final int palevioletred=0x7f04007f;
        public static final int papayawhip=0x7f040080;
        public static final int peachpuff=0x7f040081;
        public static final int peru=0x7f040082;
        public static final int pink=0x7f040083;
        public static final int plum=0x7f040084;
        public static final int powderblue=0x7f040085;
        public static final int purple=0x7f040086;
        public static final int red=0x7f040087;
        public static final int rosybrown=0x7f040088;
        public static final int royalblue=0x7f040089;
        public static final int saddlebrown=0x7f04008a;
        public static final int salmon=0x7f04008b;
        public static final int sandybrown=0x7f04008c;
        public static final int seaShell=0x7f04008d;
        public static final int seagreen=0x7f04008e;
        public static final int sienna=0x7f04008f;
        public static final int silver=0x7f040090;
        public static final int skyblue=0x7f040091;
        public static final int slateblue=0x7f040092;
        public static final int slategray=0x7f040093;
        public static final int slategrey=0x7f040094;
        public static final int snow=0x7f040095;
        public static final int springgreen=0x7f040096;
        public static final int steelblue=0x7f040097;
        public static final int tan=0x7f040098;
        public static final int teal=0x7f040099;
        public static final int thistle=0x7f04009a;
        public static final int tomato=0x7f04009b;
        public static final int transparent=0x7f04009c;
        public static final int turquoise=0x7f04009d;
        public static final int violet=0x7f04009e;
        public static final int wheat=0x7f04009f;
        public static final int white=0x7f0400a0;
        public static final int whitesmoke=0x7f0400a1;
        public static final int yellow=0x7f0400a2;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int bg=0x7f020000;
        public static final int ic_launcher=0x7f020001;
    }
    public static final class id {
        public static final int action_settings=0x7f090001;
        public static final int tab=0x7f090000;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
    public static final class menu {
        public static final int menu_main=0x7f080000;
    }
    public static final class string {
        public static final int action_settings=0x7f060000;
        public static final int app_name=0x7f060001;
        public static final int hello_world=0x7f060002;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f070000;
    }
    public static final class styleable {
        /** Attributes that can be used with a ActionSheet.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ActionSheet_actionSheetBackground com.example.zhangxingyu.myapplication:actionSheetBackground}</code></td><td></td></tr>
           <tr><td><code>{@link #ActionSheet_actionSheetPadding com.example.zhangxingyu.myapplication:actionSheetPadding}</code></td><td></td></tr>
           <tr><td><code>{@link #ActionSheet_actionSheetTextSize com.example.zhangxingyu.myapplication:actionSheetTextSize}</code></td><td></td></tr>
           <tr><td><code>{@link #ActionSheet_cancelButtonBackground com.example.zhangxingyu.myapplication:cancelButtonBackground}</code></td><td></td></tr>
           <tr><td><code>{@link #ActionSheet_cancelButtonMarginTop com.example.zhangxingyu.myapplication:cancelButtonMarginTop}</code></td><td></td></tr>
           <tr><td><code>{@link #ActionSheet_cancelButtonTextColor com.example.zhangxingyu.myapplication:cancelButtonTextColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ActionSheet_otherButtonBottomBackground com.example.zhangxingyu.myapplication:otherButtonBottomBackground}</code></td><td></td></tr>
           <tr><td><code>{@link #ActionSheet_otherButtonMiddleBackground com.example.zhangxingyu.myapplication:otherButtonMiddleBackground}</code></td><td></td></tr>
           <tr><td><code>{@link #ActionSheet_otherButtonSingleBackground com.example.zhangxingyu.myapplication:otherButtonSingleBackground}</code></td><td></td></tr>
           <tr><td><code>{@link #ActionSheet_otherButtonSpacing com.example.zhangxingyu.myapplication:otherButtonSpacing}</code></td><td></td></tr>
           <tr><td><code>{@link #ActionSheet_otherButtonTextColor com.example.zhangxingyu.myapplication:otherButtonTextColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ActionSheet_otherButtonTopBackground com.example.zhangxingyu.myapplication:otherButtonTopBackground}</code></td><td></td></tr>
           </table>
           @see #ActionSheet_actionSheetBackground
           @see #ActionSheet_actionSheetPadding
           @see #ActionSheet_actionSheetTextSize
           @see #ActionSheet_cancelButtonBackground
           @see #ActionSheet_cancelButtonMarginTop
           @see #ActionSheet_cancelButtonTextColor
           @see #ActionSheet_otherButtonBottomBackground
           @see #ActionSheet_otherButtonMiddleBackground
           @see #ActionSheet_otherButtonSingleBackground
           @see #ActionSheet_otherButtonSpacing
           @see #ActionSheet_otherButtonTextColor
           @see #ActionSheet_otherButtonTopBackground
         */
        public static final int[] ActionSheet = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b
        };
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#actionSheetBackground}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          @attr name com.example.zhangxingyu.myapplication:actionSheetBackground
        */
        public static final int ActionSheet_actionSheetBackground = 0;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#actionSheetPadding}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
          @attr name com.example.zhangxingyu.myapplication:actionSheetPadding
        */
        public static final int ActionSheet_actionSheetPadding = 8;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#actionSheetTextSize}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
          @attr name com.example.zhangxingyu.myapplication:actionSheetTextSize
        */
        public static final int ActionSheet_actionSheetTextSize = 11;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#cancelButtonBackground}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          @attr name com.example.zhangxingyu.myapplication:cancelButtonBackground
        */
        public static final int ActionSheet_cancelButtonBackground = 1;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#cancelButtonMarginTop}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
          @attr name com.example.zhangxingyu.myapplication:cancelButtonMarginTop
        */
        public static final int ActionSheet_cancelButtonMarginTop = 10;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#cancelButtonTextColor}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          @attr name com.example.zhangxingyu.myapplication:cancelButtonTextColor
        */
        public static final int ActionSheet_cancelButtonTextColor = 6;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#otherButtonBottomBackground}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          @attr name com.example.zhangxingyu.myapplication:otherButtonBottomBackground
        */
        public static final int ActionSheet_otherButtonBottomBackground = 4;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#otherButtonMiddleBackground}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          @attr name com.example.zhangxingyu.myapplication:otherButtonMiddleBackground
        */
        public static final int ActionSheet_otherButtonMiddleBackground = 3;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#otherButtonSingleBackground}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          @attr name com.example.zhangxingyu.myapplication:otherButtonSingleBackground
        */
        public static final int ActionSheet_otherButtonSingleBackground = 5;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#otherButtonSpacing}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
          @attr name com.example.zhangxingyu.myapplication:otherButtonSpacing
        */
        public static final int ActionSheet_otherButtonSpacing = 9;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#otherButtonTextColor}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          @attr name com.example.zhangxingyu.myapplication:otherButtonTextColor
        */
        public static final int ActionSheet_otherButtonTextColor = 7;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#otherButtonTopBackground}
          attribute's value can be found in the {@link #ActionSheet} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          @attr name com.example.zhangxingyu.myapplication:otherButtonTopBackground
        */
        public static final int ActionSheet_otherButtonTopBackground = 2;
        /** Attributes that can be used with a ActionSheets.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ActionSheets_actionSheetStyle com.example.zhangxingyu.myapplication:actionSheetStyle}</code></td><td></td></tr>
           </table>
           @see #ActionSheets_actionSheetStyle
         */
        public static final int[] ActionSheets = {
            0x7f01000c
        };
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#actionSheetStyle}
          attribute's value can be found in the {@link #ActionSheets} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.example.zhangxingyu.myapplication:actionSheetStyle
        */
        public static final int ActionSheets_actionSheetStyle = 0;
        /** Attributes that can be used with a PagerSlidingTabStrip.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_pstsDividerColor com.example.zhangxingyu.myapplication:pstsDividerColor}</code></td><td></td></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_pstsDividerPadding com.example.zhangxingyu.myapplication:pstsDividerPadding}</code></td><td></td></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_pstsIndicatorColor com.example.zhangxingyu.myapplication:pstsIndicatorColor}</code></td><td></td></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_pstsIndicatorHeight com.example.zhangxingyu.myapplication:pstsIndicatorHeight}</code></td><td></td></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_pstsScrollOffset com.example.zhangxingyu.myapplication:pstsScrollOffset}</code></td><td></td></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_pstsShouldExpand com.example.zhangxingyu.myapplication:pstsShouldExpand}</code></td><td></td></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_pstsTabBackground com.example.zhangxingyu.myapplication:pstsTabBackground}</code></td><td></td></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_pstsTabPaddingLeftRight com.example.zhangxingyu.myapplication:pstsTabPaddingLeftRight}</code></td><td></td></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_pstsTextAllCaps com.example.zhangxingyu.myapplication:pstsTextAllCaps}</code></td><td></td></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_pstsUnderlineColor com.example.zhangxingyu.myapplication:pstsUnderlineColor}</code></td><td></td></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_pstsUnderlineHeight com.example.zhangxingyu.myapplication:pstsUnderlineHeight}</code></td><td></td></tr>
           <tr><td><code>{@link #PagerSlidingTabStrip_selectedTabTextColor com.example.zhangxingyu.myapplication:selectedTabTextColor}</code></td><td></td></tr>
           </table>
           @see #PagerSlidingTabStrip_pstsDividerColor
           @see #PagerSlidingTabStrip_pstsDividerPadding
           @see #PagerSlidingTabStrip_pstsIndicatorColor
           @see #PagerSlidingTabStrip_pstsIndicatorHeight
           @see #PagerSlidingTabStrip_pstsScrollOffset
           @see #PagerSlidingTabStrip_pstsShouldExpand
           @see #PagerSlidingTabStrip_pstsTabBackground
           @see #PagerSlidingTabStrip_pstsTabPaddingLeftRight
           @see #PagerSlidingTabStrip_pstsTextAllCaps
           @see #PagerSlidingTabStrip_pstsUnderlineColor
           @see #PagerSlidingTabStrip_pstsUnderlineHeight
           @see #PagerSlidingTabStrip_selectedTabTextColor
         */
        public static final int[] PagerSlidingTabStrip = {
            0x7f01000d, 0x7f01000e, 0x7f01000f, 0x7f010010,
            0x7f010011, 0x7f010012, 0x7f010013, 0x7f010014,
            0x7f010015, 0x7f010016, 0x7f010017, 0x7f010018
        };
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#pstsDividerColor}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:pstsDividerColor
        */
        public static final int PagerSlidingTabStrip_pstsDividerColor = 2;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#pstsDividerPadding}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:pstsDividerPadding
        */
        public static final int PagerSlidingTabStrip_pstsDividerPadding = 5;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#pstsIndicatorColor}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:pstsIndicatorColor
        */
        public static final int PagerSlidingTabStrip_pstsIndicatorColor = 0;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#pstsIndicatorHeight}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:pstsIndicatorHeight
        */
        public static final int PagerSlidingTabStrip_pstsIndicatorHeight = 3;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#pstsScrollOffset}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:pstsScrollOffset
        */
        public static final int PagerSlidingTabStrip_pstsScrollOffset = 7;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#pstsShouldExpand}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:pstsShouldExpand
        */
        public static final int PagerSlidingTabStrip_pstsShouldExpand = 9;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#pstsTabBackground}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.example.zhangxingyu.myapplication:pstsTabBackground
        */
        public static final int PagerSlidingTabStrip_pstsTabBackground = 8;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#pstsTabPaddingLeftRight}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:pstsTabPaddingLeftRight
        */
        public static final int PagerSlidingTabStrip_pstsTabPaddingLeftRight = 6;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#pstsTextAllCaps}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:pstsTextAllCaps
        */
        public static final int PagerSlidingTabStrip_pstsTextAllCaps = 10;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#pstsUnderlineColor}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:pstsUnderlineColor
        */
        public static final int PagerSlidingTabStrip_pstsUnderlineColor = 1;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#pstsUnderlineHeight}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:pstsUnderlineHeight
        */
        public static final int PagerSlidingTabStrip_pstsUnderlineHeight = 4;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#selectedTabTextColor}
          attribute's value can be found in the {@link #PagerSlidingTabStrip} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:selectedTabTextColor
        */
        public static final int PagerSlidingTabStrip_selectedTabTextColor = 11;
        /** Attributes that can be used with a SegmentedTabGroup.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #SegmentedTabGroup_stgDividerColor com.example.zhangxingyu.myapplication:stgDividerColor}</code></td><td></td></tr>
           <tr><td><code>{@link #SegmentedTabGroup_stgDividerWidth com.example.zhangxingyu.myapplication:stgDividerWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #SegmentedTabGroup_stgRadius com.example.zhangxingyu.myapplication:stgRadius}</code></td><td></td></tr>
           <tr><td><code>{@link #SegmentedTabGroup_stgSelectedTabTextColor com.example.zhangxingyu.myapplication:stgSelectedTabTextColor}</code></td><td></td></tr>
           </table>
           @see #SegmentedTabGroup_stgDividerColor
           @see #SegmentedTabGroup_stgDividerWidth
           @see #SegmentedTabGroup_stgRadius
           @see #SegmentedTabGroup_stgSelectedTabTextColor
         */
        public static final int[] SegmentedTabGroup = {
            0x7f010019, 0x7f01001a, 0x7f01001b, 0x7f01001c
        };
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#stgDividerColor}
          attribute's value can be found in the {@link #SegmentedTabGroup} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:stgDividerColor
        */
        public static final int SegmentedTabGroup_stgDividerColor = 0;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#stgDividerWidth}
          attribute's value can be found in the {@link #SegmentedTabGroup} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:stgDividerWidth
        */
        public static final int SegmentedTabGroup_stgDividerWidth = 2;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#stgRadius}
          attribute's value can be found in the {@link #SegmentedTabGroup} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:stgRadius
        */
        public static final int SegmentedTabGroup_stgRadius = 3;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#stgSelectedTabTextColor}
          attribute's value can be found in the {@link #SegmentedTabGroup} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:stgSelectedTabTextColor
        */
        public static final int SegmentedTabGroup_stgSelectedTabTextColor = 1;
        /** Attributes that can be used with a clear_edit_style.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #clear_edit_style_button_type com.example.zhangxingyu.myapplication:button_type}</code></td><td></td></tr>
           <tr><td><code>{@link #clear_edit_style_right_image com.example.zhangxingyu.myapplication:right_image}</code></td><td></td></tr>
           </table>
           @see #clear_edit_style_button_type
           @see #clear_edit_style_right_image
         */
        public static final int[] clear_edit_style = {
            0x7f01001d, 0x7f01001e
        };
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#button_type}
          attribute's value can be found in the {@link #clear_edit_style} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:button_type
        */
        public static final int clear_edit_style_button_type = 0;
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#right_image}
          attribute's value can be found in the {@link #clear_edit_style} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.example.zhangxingyu.myapplication:right_image
        */
        public static final int clear_edit_style_right_image = 1;
        /** Attributes that can be used with a slider_listview_style.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #slider_listview_style_right_width com.example.zhangxingyu.myapplication:right_width}</code></td><td></td></tr>
           </table>
           @see #slider_listview_style_right_width
         */
        public static final int[] slider_listview_style = {
            0x7f01001f
        };
        /**
          <p>This symbol is the offset where the {@link com.example.zhangxingyu.myapplication.R.attr#right_width}
          attribute's value can be found in the {@link #slider_listview_style} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.zhangxingyu.myapplication:right_width
        */
        public static final int slider_listview_style_right_width = 0;
    };
}
