package com.anappforthat.android.languagelineup;

/**
 * Created by root on 1/5/15.
 */
public class LanguageStringArrayLastEightLanguages {

    String[][] array  = {{"能夠", "關於", "以上", "橫過", "法案", "行動", "其實", "加", "加法",
            "形容詞", "害怕", "非洲", "後", "再次", "針對", "年齡", "前", "同意", "向前",
            "空氣", "所有", "允許", "幾乎", "獨", "沿", "已經", "還", "雖然", "總是",
            "上午", "美國", "中", "量", "和", "角", "動物", "另一", "答案", "任何",
            "什麼", "出現", "蘋果", "有", "區域", "武器", "軍隊", "圍繞", "抵達", "藝術",
            "如", "問", "在", "遠", "寶寶", "後面", "壞", "球", "銀行", "基地", "是",
            "承擔", "打", "美麗", "成為", "因為", "成為", "床", "一直", "前", "開始",
            "開始", "背後", "存在", "相信", "鐘", "屬於", "下面", "旁", "最好的", "更好",
            "之間", "大", "法案", "鳥類", "位", "黑色", "塊", "血", "打擊", "藍色",
            "板", "船", "體", "骨頭", "書", "天生的", "兩", "底部", "箱", "男孩",
            "分支機構", "休息", "光明", "把", "英國的", "破", "哥", "帶來", "棕色", "建",
            "建築", "建", "燃燒", "業務", "但", "購買", "通過", "通話", "來了", "可以",
            "不能", "不能", "資本", "隊長", "汽車", "關懷", "小心", "攜帶", "案", "貓",
            "抓", "黃牛", "抓", "原因", "細胞", "中心", "仙", "世紀", "某些", "機會",
            "變化", "圖", "查", "首席", "孩子", "孩子", "選擇", "教堂", "圈", "城市",
            "類", "清潔", "明確", "攀", "關閉", "衣服", "雲", "濱", "冷", "顏色", "柱",
            "來", "常見", "公司", "比較", "完整", "複合", "條件", "考慮", "輔音", "遏制",
            "持續", "控制", "廚師", "冷靜", "複製", "玉米", "角落", "正確", "成本", "棉",
            "可以", "不能", "算", "國家", "課程", "覆蓋", "牛", "創建", "哭了", "作物",
            "交叉", "人群", "當前", "切", "舞蹈", "暗", "日", "死", "合同", "死亡",
            "決定", "十進制", "深", "描述", "沙漠", "設計", "詳細信息", "確定", "發達",
            "字典", "做", "沒有", "死亡", "差異", "不同", "難", "直接", "方向", "發現",
            "距離", "分", "師", "做", "醫生", "不", "不", "狗", "美元", "DONE",
            "門", "向下", "畫", "圖", "連衣裙", "驅動器", "降", "幹", "中", "每", "早",
            "耳朵", "土", "東", "易", "吃", "邊緣", "效果", "雞蛋", "八", "或", "電動",
            "分子", "其他", "結束", "能源", "發動機", "英國", "英語", "享受", "夠了",
            "進入", "整個", "等於", "方程", "尤其", "歐洲", "甚至", "黃昏", "永遠", "一切",
            "大家", "一切", "究竟", "例子", "除", "扣人心弦", "鍛煉", "期望", "經驗",
            "實驗", "說明", "表達", "表達的", "眼", "臉", "事實", "工廠", "因素", "下降",
            "家庭", "著名", "遠", "農場", "農民", "快", "父親", "恐懼", "感覺", "感覺",
            "腳", "下跌", "氈", "少數", "場", "無花果", "打", "數字", "填充", "最後",
            "發現", "精", "手指", "完", "火", "第一", "魚", "需要", "五", "平", "地板",
            "流", "花卉", "飛", "跟隨", "食物", "腳", "為", "力", "森林", "表格",
            "向前", "發現", "四", "分數", "法國", "免費", "法國人", "新鮮", "朋友", "從",
            "前", "水果", "滿", "有趣", "遊戲", "花園", "氣", "給", "一般", "得到",
            "女孩", "給", "玻璃", "去", "上帝", "金", "過去的", "好", "有", "政府",
            "草", "大", "希臘語", "綠色", "增長", "地面", "組", "增長", "猜", "槍",
            "有", "發", "停止", "手", "發生", "快樂", "硬", "有", "帽子", "有", "他",
            "頭", "聽", "聽說", "心臟", "熱", "重", "保持", "幫助", "她的", "這裡",
            "高", "山", "他", "他自己", "他的", "歷史", "撞", "持有", "孔", "家",
            "希望", "馬", "熱", "小時", "房子", "如何", "然而", "巨大", "人的", "百",
            "狩獵", "我", "冰", "想法", "如果", "我會", "重要", "在", "英寸", "包括",
            "增加", "印度", "指示", "行業", "信息", "昆蟲", "內", "代替", "儀器", "興趣",
            "成", "鐵", "是", "島", "不", "它", "其", "它的", "本身", "日本", "工作",
            "加盟", "跳", "剛", "堅持，稍等！", "保持", "關鍵", "打死", "樣", "王", "知道",
            "我知道", "已知", "女士", "湖", "土地", "語", "大", "最後", "後來", "笑了",
            "法", "打好", "領導", "學習", "最少", "離開", "LED", "左", "腿", "長度",
            "少", "讓", "讓我們", "信", "級別", "謊言", "生活", "解除", "光", "喜歡",
            "線", "表", "聽", "小", "生活", "位於", "長", "看", "丟", "很多", "響",
            "愛", "低", "機", "做", "主", "主要", "使", "男人", "許多", "地圖", "遊行",
            "標誌", "比賽", "材料", "事", "可", "也許", "我", "意味著", "測量", "肉",
            "滿足", "旋律", "成員", "男人", "金屬", "方法", "中間", "威力", "英里", "牛奶",
            "百萬", "頭腦", "礦", "分鐘", "錯過", "現代", "分子", "瞬間", "金錢", "個月",
            "月亮", "更多", "早晨", "最", "母親", "山", "口", "移動", "運動", "多",
            "音樂", "必須", "我的", "名稱", "國家", "自然", "近", "必要", "需要",
            "從來沒有", "新", "下一個", "夜", "無", "也不", "北", "北方", "鼻子", "不",
            "注", "無", "通知", "名詞", "現在", "數", "數字", "物體", "守", "海洋",
            "的", "離", "辦公室", "常", "哦", "油", "老", "上", "一旦", "一", "只",
            "開", "相反", "或", "順序", "其他", "我們的", "出", "外", "以上", "獨立地",
            "氧", "頁面", "漆", "對", "紙", "段", "公園", "部分", "特別是", "黨",
            "通過", "過去", "模式", "付", "人", "每", "也許", "期", "人", "短語",
            "採摘的", "圖片", "片", "地方", "平原", "計劃", "機", "廠", "植物", "玩",
            "請", "複數", "詩", "點", "極", "差", "位置", "可能", "英鎊", "功率",
            "實踐", "準備", "總統", "漂亮", "印刷的", "大概", "問題", "過程", "生產",
            "雜貨", "屬性", "提供", "拉", "推", "放", "問題", "很快", "安靜", "相當",
            "種族", "收音機", "雨", "凸", "然", "寧", "達", "閱讀", "準備", "真",
            "原因", "收到", "記錄", "紅", "區域", "留", "記得", "反复", "報告", "代表",
            "憤慨", "休息", "結果", "回歸", "韻律", "豐富", "騎", "右邊", "環", "上升",
            "河", "道路", "岩石", "熱軋", "房間", "根", "繩", "玫瑰", "圓", "排",
            "規則", "運行", "安全", "說", "帆", "同", "沙", "坐", "保存", "鋸", "說",
            "規模", "學校", "科學", "科學家", "得分", "海", "座位", "第二", "部分", "看",
            "種子", "似乎", "可見", "賣", "發送", "感", "發送", "句子", "另", "服務",
            "集", "安定", "七", "幾個", "將", "形狀", "銳", "她", "船", "鞋", "店",
            "短", "應", "肩", "喊", "節目", "顯示", "側", "視力", "標誌", "信號",
            "無聲", "類似", "簡單", "自", "唱", "先生", "妹妹", "坐", "六", "大小",
            "皮膚", "天空", "睡覺", "慢慢地", "小", "聞", "微笑", "雪", "所以", "軟",
            "土壤", "戰士", "解", "一些", "誰", "某物", "有時", "兒子", "歌", "不久",
            "聲音", "南", "南部的", "空間", "說話", "特別", "速度", "拼", "現場", "傳播",
            "春天", "方", "站", "明星", "開始", "態", "聲明", "留", "鋼", "步", "棒",
            "還", "石", "站在", "停止", "店", "故事", "直", "奇怪", "流", "街頭",
            "拉伸", "串", "強烈", "學生", "研究", "主題", "物質", "這樣", "突然", "後綴",
            "糖", "建議", "總和", "夏天", "太陽", "供應", "假設", "肯定", "表面", "驚",
            "游泳", "音節", "符號", "系統", "表", "尾", "取", "談話", "高", "老師",
            "團隊", "告訴", "溫度", "十", "條款", "測試", "比", "那", "他們的", "他們",
            "他們自己", "然後", "那裡", "這些", "他們", "厚", "薄", "事", "想", "第三",
            "這", "那些", "雖然", "思想", "數千", "三", "通過", "從而", "綁", "時間",
            "小", "向（以）", "今天", "一起", "告訴", "音", "太", "花", "工具", "頂部",
            "總", "觸摸", "往", "鎮", "軌道", "貿", "火車", "旅遊", "樹", "三角形",
            "旅", "麻煩", "卡車", "真", "嘗試", "管", "轉", "二", "類型", "叔叔", "下",
            "強調", "明白", "單位", "直到", "向上", "上", "我們", "使用", "平時", "谷",
            "值", "各個", "動詞", "很", "視圖", "村", "訪問", "聲音", "元音", "等待！",
            "走", "牆", "想要", "戰爭", "溫暖", "為", "洗", "華盛頓", "不", "看", "水",
            "波浪", "否則", "我們", "穿", "天氣", "週", "重量", "好", "我們會", "去",
            "為", "西", "西", "什麼", "車輪", "何時", "哪裡", "是否", "哪", "而", "白",
            "誰", "全", "誰", "為什麼", "寬", "妻子", "野", "將", "贏", "風", "窗口",
            "翅膀", "冬天", "線", "希望", "同", "內", "無", "女人", "女", "奇蹟",
            "不會", "木", "字", "工作", "工人", "世界", "會這麼做", "不會做", "寫", "書面",
            "錯", "寫", "碼", "年", "黃色", "是的", "但", "您", "年輕", "您的", "你自己"},

        {"kunnen ", "over ", "boven ", "over ", "daad ",
                "actie ", "werkelijk ", "toevoegen ", "toevoeging ",
                "adjectief ", "bang te zijn ", "Afrika ", "na ", "weer ",
                "tegen ", "leeftijd ", "geleden ", "afgesproken ",
                "vooruit ", "lucht ", "alle ", "toestaan ", "bijna ",
                "alleen ", "langs ", "al ", "ook ", "hoewel ", "altijd ",
                "am ", "Amerika ", "onder ", "bedrag ", "en ", "hoek ",
                "dier ", "ander ", "antwoord ", "een ", "iets ",
                "verschenen ", "appel ", "zijn ", "gebied ", "armen ",
                "leger ", "rond ", "aangekomen ", "kunst ", "als ",
                "vragen ", "bij ", "weg ", "baby ", "terug ", "slecht ",
                "bal ", "bank ", "base ", "zijn ", "dragen ", "slaan ",
                "mooi ", "werd ", "omdat ", "worden ", "bed ", "geweest ",
                "voor ", "begon ", "beginnen ", "achter ", "zijnde ",
                "geloven ", "bel ", "behoren ", "onder ", "naast ",
                "best ", "beter ", "tussen ", "groot ", "rekening ",
                "vogelstand ", "bit ", "zwart ", "blok ", "bloed ",
                "klap ", "blauw ", "boord ", "boot ", "lichaam ",
                "beenderen ", "boek ", "geboren ", "beide ", "bodem ",
                "doos ", "jongen ", "takken ", "breken ", "helder ",
                "brengen ", "Brits ", "gebroken ", "broer ", "bracht ",
                "bruin ", "bouwen ", "gebouw ", "gebouwd ", "brandend ",
                "bedrijf ", "maar ", "kopen ", "door ", "roep ", "kwam ",
                "kan ", "kan niet ", "kan niet ", "kapitaal ", "kapitein ",
                "auto ", "zorg ", "voorzichtig ", "dragen ", "geval ",
                "kat ", "vangst ", "vee ", "gevangen ", "oorzaak ",
                "cellen ", "centrum ", "cent ", "eeuw ", "zeker ", "kans ",
                "verandering ", "tabel ", "controleren ", "chef ", "kind ",
                "kinderen ", "kiezen ", "kerk ", "cirkel ", "stad ",
                "klasse ", "schoon ", "duidelijk ", "klom ", "dicht ",
                "kleren ", "wolk ", "kust ", "koud ", "kleur ", "kolom ",
                "komen ", "gemeenschappelijk ", "vennootschap ",
                "vergelijken ", "compleet ", "samenstelling ",
                "voorwaarden ", "te overwegen ", "medeklinker ",
                "bevatten ", "vervolgd ", "controle ", "kok ", "koel ",
                "kopie ", "maïs ", "hoek ", "juist ", "kosten ", "katoen ",
                "kon ", "kon niet ", "tellen ", "land ", "cursus ",
                "gedekt ", "koeien ", "creëren ", "riep ", "gewassen ",
                "oversteken ", "menigte ", "stroom ", "gesneden ", "dans ",
                "donker ", "dag ", "dood ", "transactie ", "dood ",
                "beslist ", "decimale ", "diep ", "beschrijven ",
                "woestijn ", "ontwerp ", "Details ", "bepalen ",
                "ontwikkelde ", "woordenboek ", "deed ", "niet ",
                "gestorven ", "verschil ", "verschillend ", "moeilijk ",
                "direct ", "richting ", "ontdekt ", "afstand ",
                "verdeeld ", "divisie ", "doen ", "dokter ", "doet ",
                "niet ", "hond ", "dollars ", "gedaan ", "deur ",
                "beneden ", "trekken ", "tekening ", "kleding ", "rit ",
                "drop ", "droog ", "gedurende ", "elk ", "vroeg ", "oren ",
                "aarde ", "oosten ", "gemakkelijk ", "eten ", "rand ",
                "effect ", "eieren ", "acht ", "beide ", "elektrisch ",
                "communie ", "anders ", "einde ", "energie ", "motor ",
                "Engeland ", "Engels ", "genieten ", "genoeg ",
                "ingevoerd ", "geheel ", "gelijk ", "vergelijking ",
                "vooral ", "Europa ", "zelfs ", "avond ", "ooit ",
                "iedere ", "iedereen ", "alles ", "precies ", "voorbeeld ",
                "behalve ", "opwindend ", "oefening ", "verwachten ",
                "ervaring ", "experiment ", "uitleggen ",
                "uit te drukken ", "expressief ", "oog ", "gezicht ",
                "feit ", "fabrieken ", "factoren ", "vallen ", "familie ",
                "beroemd ", "ver ", "boerderij ", "boeren ", "snel ",
                "vader ", "angst ", "voelen ", "gevoel ", "voeten ",
                "viel ", "vilt ", "weinig ", "veld ", "vijg ", "strijd ",
                "figuur ", "gevuld ", "eindelijk ", "vinden ", "fijn ",
                "vingers ", "afgewerkt ", "brand ", "eerste ", "vis ",
                "nodig ", "vijf ", "flat ", "vloer ", "stromen ",
                "bloemen ", "vliegen ", "volgen ", "voedsel ", "voet ",
                "voor ", "kracht ", "bos ", "vorm ", "vooruit ",
                "gevonden ", "vier ", "fractie ", "Frankrijk ", "gratis ",
                "Frans ", "vers ", "vrienden ", "van ", "front ", "fruit ",
                "vol ", "plezier ", "spel ", "tuin ", "gas ", "gaf ",
                "algemeen ", "krijgen ", "meisje ", "geven ", "glas ",
                "gaan ", "God ", "goud ", "weg ", "goed ", "kreeg ",
                "overheid ", "gras ", "groot ", "Grieks ", "groen ",
                "groeide ", "grond ", "groep ", "groeien ", "raden ",
                "geweer ", "had ", "haar ", "halte ", "hand ", "gebeurd ",
                "gelukkig ", "hard ", "heeft ", "hoed ", "hebben ", "hij ",
                "hoofd ", "horen ", "gehoord ", "hart ", "warmte ",
                "zwaar ", "held ", "helpen ", "haar ", "hier ", "hoog ",
                "heuvel ", "hem ", "zichzelf ", "zijn ", "geschiedenis ",
                "hit ", "houden ", "gat ", "thuis ", "hopen ", "paard ",
                "heet ", "uur ", "huis ", "hoe ", "echter ", "reusachtig ",
                "menselijk ", "honderd ", "jacht ", "ik ", "ijs ", "idee ",
                "indien ", "ik zal ", "belangrijk ", "in ", "inches ",
                "omvatten ", "verhogen ", "Indië ", "aangeven ",
                "industrie ", "informatie ", "insecten ", "binnen ",
                "in plaats daarvan ", "instrumenten ", "rente ", "in ",
                "ijzer ", "is ", "eiland ", "niet ", "het ", "zijn ",
                "het ", "zelf ", "Japanse ", "baan ", "sloot ", "sprong ",
                "gewoon ", "Hold on! ", "gehouden ", "sleutel ", "gedood ",
                "soort ", "koning ", "wist ", "ik weet ", "bekend ",
                "dame ", "meer ", "land ", "taal ", "groot ", "laatste ",
                "later ", "lachte ", "wet ", "te leggen ", "om te leiden ",
                "leren ", "minst ", "vertrekken ", "geleid ", "links ",
                "benen ", "lengte ", "minder ", "laten ", "laten we ",
                "brief ", "niveau ", "leugen ", "leven ", "opgeheven ",
                "licht ", "zoals ", "lijn ", "lijst ", "luisteren ",
                "weinig ", "wonen ", "gelegen ", "lang ", "kijken ",
                "verloren ", "lot ", "luid ", "liefde ", "laag ",
                "machine ", "gemaakt ", "hoofd-", "groot ", "maken ",
                "man ", "veel ", "kaart ", "mars ", "mark ", "wedstrijd ",
                "materiaal ", "aangelegenheid ", "kunnen ", "misschien ",
                "me ", "betekenen ", "meten ", "vlees ", "ontmoeten ",
                "melodie ", "leden ", "mensen ", "metalen ", "methode ",
                "midden ", "macht ", "mijl ", "melk ", "miljoen ",
                "geest ", "de mijne ", "notulen ", "missen ", "modern ",
                "moleculen ", "moment ", "geld ", "maanden ", "maan ",
                "meer ", "ochtend ", "meest ", "moeder ", "berg ", "mond ",
                "verhuizing ", "beweging ", "veel ", "muziek ", "moet ",
                "mijn ", "naam ", "natie ", "natuurlijk ", "dichtbij ",
                "noodzakelijk ", "moeten ", "nooit ", "nieuw ",
                "volgende ", "nacht ", "geen ", "noch ", "noorden ",
                "noordelijk ", "neus ", "niet ", "noot ", "niets ",
                "kennisgeving ", "zelfstandig naamwoord ", "nu ",
                "aantal ", "cijfer ", "object ", "waarnemen ", "oceaan ",
                "van ", "af ", "kantoor ", "vaak ", "oh ", "olie ", "oud ",
                "op ", "eenmaal ", "een ", "alleen ", "open ",
                "tegenover ", "of ", "orde ", "ander ", "onze ", "uit ",
                "buiten ", "over ", "onafhankelijk ", "zuurstof ",
                "pagina ", "schilderen ", "paar ", "papier ", "paragraaf ",
                "park ", "deel ", "in het bijzonder ", "partij ",
                "voorbij ", "verleden ", "patroon ", "betalen ", "mensen ",
                "per ", "misschien ", "periode ", "persoon ", "frase ",
                "uitgekozen ", "afbeelding ", "stuk ", "plaats ",
                "vlaktes ", "plan ", "vliegtuig ", "plant ", "planten ",
                "om te spelen ", "alstublieft ", "meervoud ", "gedicht ",
                "punt ", "paal ", "arm ", "positie ", "mogelijk ",
                "ponden ", "vermogen ", "praktijk ", "bereid ",
                "presidenten ", "vrij ", "afgedrukt ", "waarschijnlijk ",
                "probleem ", "procede ", "produceren ",
                "kruidenierswaren ", "eigendom ", "voorzien ",
                "getrokken ", "geduwd ", "zetten ", "vragen ", "snel ",
                "rustig ", "heel ", "race ", "radio ", "regen ",
                "verheven ", "ran ", "eerder ", "bereikt ", "lezen ",
                "klaar ", "echt ", "reden ", "ontvangen ", "record ",
                "rood ", "regio ", "blijven ", "onthouden ", "herhaald ",
                "verslag ", "vertegenwoordigen ", "aanstoot nemen ",
                "rest ", "resultaat ", "terugkeer ", "ritme ", "rijk ",
                "rijden ", "rechts ", "ring ", "stijgen ", "rivier ",
                "weg ", "rots ", "gerold ", "kamer ", "wortel ", "touw ",
                "roze ", "ronde ", "rij ", "regel ", "lopen ", "veilig ",
                "zei ", "zeil ", "dezelfde ", "zand ", "te zitten ",
                "om op te slaan ", "zaag ", "zeggen ", "schaal ",
                "school ", "wetenschap ", "wetenschappers ", "partituur ",
                "zee ", "zetel ", "tweede ", "sectie ", "zien ", "zaden ",
                "lijken ", "gezien ", "verkopen ", "sturen ", "gevoel ",
                "verzonden ", "zin ", "apart ", "dienen ", "reeks ",
                "verrekend ", "zeven ", "verscheidene ", "zal ", "vorm ",
                "scherp ", "ze ", "schip ", "schoenen ", "winkel ",
                "kort ", "moeten ", "schouder ", "schreeuwde ", "tonen ",
                "getoond ", "kant ", "zicht ", "teken ", "signaal ",
                "stil ", "gelijk ", "eenvoudig ", "sinds ", "zingen ",
                "mijnheer ", "zus ", "zitten ", "zes ", "maat ", "huid ",
                "hemel ", "slaap ", "langzaam ", "klein ", "geur ",
                "glimlachte ", "sneeuw ", "dus ", "zacht ", "bodem ",
                "soldaten ", "oplossing ", "sommige ", "iemand ", "iets ",
                "soms ", "zoon ", "lied ", "spoedig ", "klinken ",
                "zuiden ", "zuidelijk ", "ruimte ", "spreken ",
                "speciaal ", "snelheid ", "spellen ", "plek ",
                "verspreiding ", "voorjaar ", "plein ", "staan ",
                "sterren ", "begin ", "staat ", "verklaring ", "blijven ",
                "staal ", "stap ", "stok ", "nog ", "steen ", "stond ",
                "stop ", "winkel ", "verhaal ", "rechtdoor ", "vreemd ",
                "stroom ", "straat ", "uitgerekt ", "snaar ", "sterk ",
                "studenten ", "studie ", "onderwerp ", "stoffen ",
                "dergelijk ", "plotseling ", "achtervoegsel ", "suiker ",
                "voorgesteld ", "som ", "zomer ", "zon ", "levering ",
                "veronderstellen ", "zeker ", "oppervlak ", "verrassing ",
                "zwemmen ", "lettergrepen ", "symbolen ", "systeem ",
                "tafel ", "staart ", "nemen ", "praten ", "hoog ",
                "leraar ", "team ", "vertellen ", "temperatuur ", "tien ",
                "termen ", "test ", "dan ", "dat ", "hun ", "hen ",
                "zij zich ", "dan ", "er ", "deze ", "ze ", "dik ", "dun ",
                "ding ", "denken ", "derde ", "deze ", "die ", "hoewel ",
                "gedachte ", "duizenden ", "drie ", "door ", "dus ",
                "gebonden ", "tijd ", "minuscuul ", "om (om) ", "vandaag ",
                "samen ", "vertelde ", "toon ", "ook ", "nam ",
                "gereedschap ", "top ", "totaal ", "aanraken ",
                "richting ", "stad ", "spoor ", "handel ", "trein ",
                "reizen ", "boom ", "driehoek ", "reis ", "moeite ",
                "vrachtwagen ", "waar ", "proberen ", "buis ", "beurt ",
                "twee ", "type ", "oom ", "onder ", "onderstrepen ",
                "begrijpen ", "eenheid ", "tot ", "omhoog ", "op ", "ons ",
                "gebruik ", "gewoonlijk ", "dal ", "waarde ", "divers ",
                "werkwoord ", "zeer ", "uitzicht ", "dorp ", "bezoek ",
                "stem ", "klinker ", "wachten! ", "lopen ", "muur ",
                "te willen ", "oorlog ", "warm ", "was ", "wassen ",
                "Washington ", "niet ", "horloge ", "water ", "golven ",
                "anders ", "we ", "dragen ", "weer ", "week ", "gewicht ",
                "goed ", "wij zullen ", "ging ", "waren ", "west ",
                "western ", "wat ", "wielen ", "wanneer ", "waar ", "of ",
                "die ", "terwijl ", "wit ", "die ", "geheel ", "wiens ",
                "waarom ", "breed ", "vrouw ", "wild ", "zullen ",
                "winnen ", "wind ", "venster ", "coulissen ", "winter ",
                "draad ", "wensen ", "met ", "binnen ", "zonder ",
                "vrouw ", "vrouwen ", "wonder ", "zal niet ", "hout ",
                "woord ", "werk ", "werknemers ", "wereld ",
                "dat zou doen ", "dat niet zou doen ", "schrijven ",
                "geschreven ", "mis ", "schreef ", "yard ", "jaar ",
                "geel ", "ja ", "nog ", "u ", "jong ", "uw ", "jezelf"},

        {"staat te wees om", "oor", "bo", "oor", "Wet",
                "aksie", "eintlik", "voeg", "Daarbenewens", "naamwoord",
                "bang te wees", "Afrika", "anus", "weer", "teen",
                "ouderdom", "gelede", "ooreengekom", "voor", "lug", "al",
                "toelaat", "byna", "alleen", "saam", "reeds", "so",
                "Alhoewel", "altyd", "aan die", "Amerika", "onder",
                "bedrag", "en", "hoek", "dier", "'n ander", "antwoord",
                "enige", "enigiets", "verskyn", "Apple", "is", "gebied",
                "arms", "weermag", "rondom", "aangekom", "tipe", "as",
                "vra", "op", "weg", "baba", "terug", "badkamer", "bal",
                "Bank", "basis", "wees", "dra", "klop", "pragtige",
                "geword", "omdat", "geword", "bed", "voltooi", "voor",
                "begin", "begin", "agter", "synde", "glo", "Bell",
                "behoort", "hieronder", "langs", "beste", "beter",
                "tussen", "groot", "wetsontwerp", "voëls", "bietjie",
                "Swart", "blok", "bloed", "blaas", "Blou", "direksie",
                "boot", "liggaam", "bene", "Facebook", "fontein", "beide",
                "onderkant", "box", "seuntjie", "takke", "breek", "helder",
                "te bring", "Britse", "gebreek", "broer", "gebring",
                "bruin", "bou", "gebou", "gebou", "brand", "besigheid",
                "maar", "koop", "deur", "oproep", "gekom", "kan",
                "kan nie", "kan nie", "kapitaal", "kaptein", "motor",
                "sorg", "sorg ten volle", "voer", "geval", "kat", "vangs",
                "beeste", "gevang", "oorsaak", "selle", "sentrum", "sent",
                "eeu", "sekere", "kans", "verandering", "grafiek", "check",
                "Hoof", "kind", "kinders", "kies", "kerk", "sirkel",
                "Plaas", "klas", "skoon", "duidelik", "klim", "Close",
                "klere", "wolk", "kus", "koue", "kleur", "kolom", "kom",
                "gemeenskaplike", "maatskappye", "vergelyk", "volledige",
                "verbinding", "voorwaardes", "om te oorweeg", "konsonant",
                "om die bevalling", "voortgesette", "beheer", "Cook",
                "Modern", "kopie", "koring", "hoek", "korrekte", "koste",
                "katoen", "kon", "kon nie", "tel", "land", "natuurlik",
                "bedek", "koeie", "skep", "gehuil", "gewasse", "steek",
                "skare", "huidige", "cut", "dans", "donker", "dag", "dood",
                "deal", "dood", "BESLUIT", "desimale", "diep", "beskryf",
                "woestyn", "ontwerp", "besonderhede",
                "deterministiese myn", "ontwikkelde", "woordeboek", "het",
                "het nie", "dood", "verskil", "verskillende", "moeilik",
                "direkte", "rigting", "ontdek", "afstand", "verdeel",
                "afdeling", "doen", "dokter", "doen", "doen nie", "hond",
                "dollars", "gedoen", "deur", "af", "trek", "tekening",
                "rok", "ry", "drop", "droë", "val op", "elke", "vroeë",
                "ore", "aarde", "oos", "maklik", "eet", "rand",
                "uitwerking", "eiers", "agt", "óf", "elektriese",
                "elemente", "anders", "einde", "energie", "enjin",
                "Engeland", "Engels", "geniet", "genoeg", "aangegaan",
                "hele", "gelyke", "vergelyking", "veral", "Europa",
                "selfs", "aand", "ooit", "elke", "almal", "alles",
                "presies", "byvoorbeeld", "behalwe", "opwindende",
                "oefening", "verwag", "ondervinding", "eksperiment",
                "verduidelik", "uit te druk", "uitdrukkingsvolle", "oog",
                "Facebook", "Trouens", "fabrieke", "faktore", "geval",
                "gesin", "bekende", "ver", "plaas", "boere", "byna",
                "vader", "vrees", "voel", "gevoel", "voete", "pels",
                "voel", "paar", "gebied", "Fig", "stryd", "figuur",
                "gevul", "uiteindelik", "plek", "fyn", "vingers", "klaar",
                "vuur", "Ridge", "vis", "nodig", "vyf", "plat", "vloer",
                "vloei", "blomme", "vlieg", "volg", "voedsel", "voet",
                "vir", "krag", "bos", "vorm", "vorentoe", "gevind", "vier",
                "breuk", "Frankryk", "vry", "Franse", "vars", "Vriende",
                "uit", "front", "vrugte", "volle", "pret", "spel", "tuin",
                "gas", "gegee", "algemene", "kry", "meisie", "gee", "glas",
                "gaan", "God", "goud", "weg", "goeie", "het", "regering",
                "gras", "groot", "Griekse", "Groen", "gegroei", "grond",
                "groep", "groei", "raai", "geweer", "moes", "hare", "net",
                "hand", "gebeur", "gelukkig", "hard", "het", "het", "het",
                "hey", "kop", "hoor", "gehoor", "hart", "hitte", "swaar",
                "held", "help", "hier", "hier", "hoë", "Hill", "hom",
                "homself", "sy", "geskiedenis", "getref", "hou", "gat",
                "huis", "hoop", "Perd", "warm", "uur", "huis", "hoe",
                "MAAR", "groot", "menslik", "honderd", "jag", "Ek", "ys",
                "idee", "As", "Ek sal", "belangrik", "in", "duim", "sluit",
                "verhoog vergroot", "Indië", "om aan te dui wat aandui",
                "bedryf", "inligting", "insekte", "binnekant", "plaas",
                "instrumente", "belangstelling", "in", "yster", "is",
                "Ysland", "is dit nie", "dit", "sy", "dit is", "self",
                "japanese", "werk", "aangesluit", "gespring", "net",
                "hou op!", "gehou", "sleutel", "vermoor", "kind", "koning",
                "geweet", "Ek weet", "bekende", "lady", "pekel", "land",
                "taal", "groot", "vrag", "later", "lag", "wet", "te lê",
                "te lei", "leer", "minste", "verlaat", "gelei", "links",
                "bene", "lengte", "minder", "laat", "laat se", "brief",
                "vlak", "leuen", "lewe", "opgehef", "lig", "soos", "lyn",
                "geslepe", "lys", "bietjie", "lewe", "geleë", "lang",
                "kyk", "verloor", "soldeersel", "groot", "liefde", "lae",
                "masjien", "grub", "Main", "groot", "maak", "een", "baie",
                "kaart", "Maart", "murg", "wedstryd", "materiaal", "Matt",
                "mag", "Miskien", "my", "beteken", "meet", "vleis",
                "ontmoet", "melodie", "lede", "mans", "metaal", "metode",
                "middel", "mag ook", "myl", "melk", "miljoen", "gedagte",
                "myn", "minute", "mis", "moderne", "molekules", "oomblik",
                "geld", "maande", "maan", "meer", "oggend", "moet", "ma",
                "berg", "mond", "skuif", "beweging", "veel", "musiek",
                "moet", "my", "naam", "nasie", "natuurlike", "naby",
                "nodige", "nodig", "nooit", "nuwe", "volgende", "nag",
                "geen", "normale", "noord", "noordelike", "neus", "nood",
                "noot", "niks", "kennisgewing", "naamwoord", "nou",
                "aantal", "getal", "voorwerp", "neem", "Oseaan", "van",
                "af", "kantoor", "dikwels", "O", "olie", "ou", "op",
                "keer", "een", "slegs", "oop", "teenoorgestelde", "of",
                "om", "ander", "ons", "uit", "buite", "oor", "onafhanklik",
                "suurstof", "bladsy", "verf", "paar", "papier",
                "paragraaf", "park", "deel", "in die besonder",
                "partytjie", "geslaag", "verlede", "patroon", "betaal",
                "mense", "deur", "miskien", "tydperk", "persoon",
                "uitdrukking", "opgetel", "prentjie", "stukkie", "plek",
                "vlaktes", "vliegtuig", "seil", "planne", "plante",
                "om te speel", "asseblief", "meervoud", "gedig", "punt",
                "paal", "swak", "posisie", "moontlik", "pond", "krag",
                "praktyk", "voorberei", "presidente", "mooi", "gedruk",
                "waarskynlik", "probleem", "proses", "te produseer",
                "kruideniersware", "eiendom", "te Voorsien", "getrek",
                "gestoot", "sit", "vrae", "vinnig", "stil", "baie",
                "wedloop", "radio", "reën", "opgewek", "hardloop",
                "eerder", "bereik", "lees", "gereed", "regtig", "rede",
                "ontvang", "rekord", "rooi", "streek", "BLY", "onthou",
                "herhaal", "verslag", "verteenwoordig", "aanstoot",
                "oorblywende", "gevolg", "terugkeer", "ritme", "ryk",
                "te ry", "reg", "ring", "styg", "rivier", "pad", "rock",
                "gerol", "kamer", "wortel", "tou", "roos", "ronde", "ry",
                "reël", "hardloop", "veilige", "gesê", "vaar", "saad",
                "sand", "om te sit", "te red", "saag", "sê", "skaal",
                "skool", "wetenskap", "wetenskaplikes", "telling", "see",
                "stoel", "tweede", "artikel", "meer", "sade", "lyk",
                "mere", "maatskappy", "stuur", "sens", "gestuur", "vonnis",
                "afsonderlike", "dien", "stel", "vereffen", "sewe",
                "verskeie", "sal", "vorm", "skerp", "sy", "skip", "skoene",
                "shop", "kort", "shoulderstand", "skouer", "geskree",
                "show", "getoon", "kant", "oë", "teken", "sein", "stil",
                "soortgelyke", "eenvoudige", "sedert", "sing", "meneer",
                "suster", "sit", "ses", "grootte", "vel", "lug", "slaap",
                "stadig", "klein", "reuk", "glimlag", "sneeu", "so",
                "sagte", "grond", "soldate", "oplossing", "sommige",
                "iemand", "iets", "soms", "maar", "lied", "gou", "klink",
                "Suid-suidelike", "ruimte", "praat", "spesiale", "spoed",
                "spel", "kommersiële", "verspreiding", "die lente",
                "vierkante", "staan", "sterre", "begin", "staat",
                "verklaring", "bly", "staal", "stap", "stok", "nog steeds",
                "klip", "staan", "stop", "Store", "storie", "reguit",
                "vreemde", "stroom", "straat", "uitgestrek", "string",
                "sterk", "studente", "studie", "onderwerp", "stowwe",
                "Soek", "skielik", "agtervoegsel", "suiker", "voorgestel",
                "som", "sirene", "Sondag", "toevoer", "veronderstel",
                "seker", "oppervlak", "verrassing", "swem", "lettergrepe",
                "simbole", "stelsel", "tafel", "stert", "neem", "talk",
                "hoog", "onderwyser", "span", "vertel", "temperatuur",
                "ste", "terme", "toets", "as", "het", "hulle", "hulle",
                "hulle het self", "dan", "daar", "proefskrif", "hulle",
                "dik", "dun", "ding", "dink", "derde", "hierdie",
                "diegene", "al", "gedagte", "duisende", "drie", "deur",
                "Malthus", "vasgebind", "tyd", "klein", "tot (ten einde)",
                "Vandag", "saam", "vertel", "toon", "te", "het",
                "gereedskap", "top", "totale", "raak", "teenoor", "dorp",
                "spoor", "handel", "trein", "Reis", "boom", "driehoek",
                "trip", "moeilikheid", "vragmotor", "ware", "probeer",
                "buisie", "beurt", "twee", "Graad", "oom", "onder",
                "onderstreep", "verstaan", "eenheid", "totdat", "up", "op",
                "ons", "te gebruik", "gewoonlik", "vallei", "waarde",
                "verskillende", "werkwoord", "baie", "View", "dorpie",
                "besoek", "stem", "vokaal", "wag!", "loop", "voorskans",
                "te wil", "was", "warm", "wat", "Was", "Washington",
                "was nie", "kyk", "water", "golwe", "anders", "ons", "dra",
                "Weer", "week", "gewig", "goed", "ons sal", "het", "was",
                "West", "Wes-wat", "wiele", "wanneer", "waar", "of",
                "watter", "terwyl", "wit", "wat", "groothandel", "wie se",
                "Hoekom", "wye", "vrou", "wilde", "wil", "wen", "wind",
                "venster", "vlerke", "winter", "draad", "wens", "met",
                "binne", "sonder", "vrou", "vroue", "wonderland",
                "sal nie", "hout", "woord", "werk", "werkers", "wêreld",
                "sou doen", "sou dit nie doen nie", "skryf", "geskryf",
                "verkeerd", "geskryf", "agterplaas", "jaar", "geel", "Ja",
                "nog", "jy", "jong", "jou", "jouself"},

        {"edebilmek", "hakkında", "yukarıdaki", "karşısında",
                "hareket", "eylem", "aslında", "eklemek", "ek", "sıfat",
                "Korkmana", "Afrika", "anüs", "tekrar", "karşı", "yaş",
                "önce", "kabul", "önde", "hava", "tüm", "izin vermek",
                "neredeyse", "tek başına", "boyunca", "zaten", "bu yüzden",
                "rağmen", "her zaman", "at", "Amerika", "arasında",
                "miktar", "ve", "açı", "hayvan", "başka", "cevap",
                "herhangi", "bir şey", "çıktı", "elma", "vardır", "alan",
                "silâh", "ordu", "etrafında", "geldi", "tip", "olarak",
                "sormak", "at", "uzakta", "bebek", "geri", "banyo", "top",
                "Banka", "baz", "olmak", "ayı", "dövmek", "güzel", "oldu",
                "çünkü", "olmak", "yatak", "tamamlandı", "önce", "başladı",
                "başla", "arkasında", "olma", "inanmak", "çan", "Belong",
                "aşağıda", "yanında", "en iyi", "daha iyi", "arasında",
                "büyük", "fatura", "kuşlar", "bit", "siyah", "blok", "kan",
                "darbe", "mavi", "tahta", "tekne", "vücut", "kemikler",
                "facebook", "pınar", "her ikisi de", "alt", "kutu",
                "oğlan", "dalları", "mola", "parlak", "getirmek",
                "İngilizler", "kırık", "kardeş", "getirdi", "kahverengi",
                "inşa etmek", "bina", "yapılı", "yanan", "iş", "ancak",
                "satın almak", "tarafından", "çağrı", "geldi", "-ebilmek",
                "Yapamam", "Yapamam", "sermaye", "kaptan", "araba",
                "bakım", "tam bakım", "taşımak", "dava", "kedi",
                "yakalamak", "sığırlar", "yakalandı", "neden", "hücreler",
                "merkez", "sent", "yüzyıl", "belli", "şans", "değişim",
                "grafik", "kontrol", "baş", "çocuk", "çocuklar", "seçmek",
                "kilise", "daire", "şehir", "sınıf", "temiz", "açık",
                "tırmandı", "yakın", "giysi", "bulut", "sahil", "soğuk",
                "renk", "sütun", "gelmek", "ortak", "şirketler",
                "karşılaştırmak", "tam", "bileşik", "koşullar", "düşünün",
                "ünsüz", "çevreleme", "devam eden", "kontrol", "aşçı",
                "serin", "kopya", "mısır", "köşe", "doğru", "maliyet",
                "pamuk", "Acaba", "yapamadım", "saymak", "ülke", "ders",
                "kapalı", "inekler", "oluşturmak", "diye bağırdı",
                "bitkileri", "çapraz", "kalabalık", "akım", "kesim",
                "dans", "karanlık", "gün", "ölü", "anlaşma", "ölüm",
                "KARAR", "ondalık", "derin", "tanımlamak", "çöl", "dizayn",
                "ayrıntılar", "deterministik mayın", "gelişmiş", "sözlük",
                "yaptım", "değil mi", "ölüm", "fark", "farklı", "zor",
                "direkt", "yön", "keşfetti", "mesafe", "bölünmüş",
                "bölünme", "do", "doktor", "yok", "etmez", "köpek",
                "dolar", "tamam", "kapı", "aşağı", "çizmek", "çizim",
                "elbise", "sürücü", "damla", "kuru", "üzerine düşen",
                "her", "erken", "kulaklar", "toprak", "doğu", "kolay",
                "yemek", "kenar", "etki", "yumurta", "sekiz", "ya da",
                "elektrik", "elementler", "başka", "son", "enerji",
                "motor", "İngiltere", "ingilizce", "hoşlanmak", "yeterli",
                "Giren", "tüm", "eşit", "denklem", "özellikle", "Avrupa",
                "hatta", "akşam", "hiç", "her", "herkes", "her şey",
                "tam olarak", "örnek", "dışında", "heyecan verici",
                "egzersiz", "beklemek", "deneyim", "deney", "açıklamak",
                "ifade etmek", "anlamlı", "göz", "facebook", "gerçek",
                "fabrikalar", "faktörler", "dava", "aile", "ünlü", "uzak",
                "çiftlik", "çiftçiler", "neredeyse", "baba", "korku",
                "hissetmek", "duygu", "ayaklar", "kürk", "keçe", "az",
                "alan", "incir", "kavga", "rakam", "dolu", "nihayet",
                "yer", "ince", "parmaklar", "bitmiş", "yangın", "sırt",
                "balık", "gerekli", "beş", "düz", "kat", "akış",
                "çiçekler", "uçmak", "takip etmek", "gıda", "ayak", "için",
                "kuvvet", "orman", "form", "ileri", "bulundu", "dört",
                "kesir", "Fransa", "ücretsiz", "Fransız", "taze",
                "arkadaşlar", "itibaren", "ön", "meyve", "tam", "eğlence",
                "oyun", "bahçe", "gaz", "verdi", "genel", "almak", "kız",
                "vermek", "cam", "gitmek", "Tanrı", "altın", "gitmiş",
                "iyi", "var", "hükümet", "çimen", "büyük", "Yunan",
                "yeşil", "büyüdü", "zemin", "grup", "büyümek", "tahmin",
                "tabanca", "vardı", "saç", "sadece", "el", "olmuş",
                "mutlu", "zor", "Has", "var", "var", "hey", "kafa",
                "duyun", "duydum", "yürek", "ısı", "ağır", "kahraman",
                "yardım", "burada", "burada", "yüksek", "tepe", "onu",
                "kendisi", "onun", "tarih", "vurmak", "tutmak", "delik",
                "ev", "umut", "at", "sıcak", "saat", "ev", "nasıl",
                "ANCAK", "kocaman", "insancıl", "yüz", "avcılık", "ben",
                "buz", "fikir", "eğer", "Ben olacak", "önemli", "içinde",
                "inç", "dahil", "Büyütme artırmak", "Hindistan",
                "belirtmek için belirten", "sanayi", "bilgi", "haşarat",
                "içeride", "yerine", "enstrümanlar", "faiz", "içine",
                "demir", "olduğunu", "İzlanda", "değil", "o", "onun",
                "bu kadar", "kendisi", "Japon", "iş", "katıldı", "atladı",
                "sadece", "tut!", "tuttu", "anahtar", "öldürdü", "çocuk",
                "kral", "Knew", "biliyorum", "bilinen", "bayan",
                "tuzlu su", "ülke", "dil", "büyük", "yük", "sonra",
                "güldü", "hukuk", "lay", "kurşun", "öğrenmek", "en az",
                "ayrılmak", "lED", "sol", "bacaklar", "uzunluk", "daha az",
                "let", "hadi", "mektup", "seviye", "yalan", "hayat",
                "kaldırdın", "ışık", "gibi", "hat", "kurnaz", "liste",
                "küçük", "canlı", "yer", "uzun", "bakmak", "kayıp",
                "lehim", "yüksek sesle", "aşk", "düşük", "makine",
                "tırtıl", "ana", "büyük", "yapmak", "bir", "çok", "harita",
                "marş", "ilik", "maç", "malzeme", "mat", "may", "belki",
                "bana", "ortalama", "ölçmek", "et", "tanışmak", "melodi",
                "üye", "erkekler", "maden", "yöntem", "orta",
                "olabilir de", "mil", "süt", "milyon", "zihin", "mayın",
                "dakika", "bayan", "modern", "molekülleri", "an", "para",
                "ay", "ay", "daha fazla", "sabah", "şart", "anne", "dağ",
                "ağız", "hareket", "hareket", "çok", "müzik", "şart",
                "benim", "isim", "ulus", "doğal", "yakın", "gerekli",
                "gerek", "asla", "yeni", "sonraki", "gece", "hayır",
                "normal", "kuzey", "kuzey", "burun", "sıkıntı", "not",
                "hiçbir şey", "uyarı", "isim", "şimdi", "numara", "rakam",
                "nesne", "gözlemek", "okyanus", "arasında", "kapalı",
                "ofis", "sık sık", "aman", "petrol", "eski", "üzerinde",
                "bir zamanlar", "bir", "sadece", "açık", "karşısında",
                "veya", "sipariş", "diğer", "bizim", "dışarı", "dışında",
                "üzerinde", "bağımsız olarak", "oksijen", "sayfa", "boya",
                "çift", "kâğıt", "paragraf", "park", "bölüm", "özellikle",
                "parti", "geçti", "geçmiş", "model", "ödeme", "insanlar",
                "tarafından", "belki", "dönem", "kişi", "ifade",
                "seçilmiş", "resim", "parça", "yer", "ovalar", "düzlem",
                "tente", "planları", "bitkiler", "oynamak", "lütfen",
                "çoğul", "şiir", "nokta", "kutup", "yoksul", "pozisyon",
                "mümkün", "lira", "güç", "uygulama", "hazırlanmış",
                "başkanlar", "güzel", "basılı", "muhtemelen", "sorun",
                "süreç", "üretmek", "bakkaliye", "özellik", "sağlayın",
                "çekti", "itti", "koymak", "sorular", "hızla", "sessiz",
                "oldukça", "yarış", "radyo", "yağmur", "yükseltilmiş",
                "ran", "oldukça", "ulaştı", "okumak", "hazır", "gerçekten",
                "neden", "alınan", "kayıt", "kırmızı", "bölge", "KALAN",
                "hatırlamak", "tekrarlanan", "rapor", "temsil etmek",
                "gücenmek", "artık", "sonuç", "dönüş", "ritim", "zengin",
                "binmek", "sağ", "halka", "artış", "nehir", "yol", "kaya",
                "haddelenmiş", "oda", "kök", "halat", "gül", "yuvarlak",
                "sıra", "kural", "çalıştırın", "güvenli", "adı geçen",
                "yelken", "tohum", "kum", "oturmak", "kaydetmek için",
                "testere", "demek", "ölçek", "okul", "bilim",
                "bilim adamları", "skor", "deniz", "koltuk", "ikinci",
                "bölüm", "göl", "tohumlar", "GÖRÜNMEYEN", "göller",
                "şirket", "göndermek", "tırpan", "gönderildi", "cümle",
                "ayrı", "hizmet etmek", "set", "yerleşik", "yedi",
                "birkaç", "Shall", "şekil", "keskin", "o", "gemi",
                "ayakkabı", "mağaza", "kısa", "shoulderstand", "omuz",
                "diye bağırdı", "gösteri", "gösterilir", "yan", "görme",
                "işaret", "işaret", "sessiz", "benzer", "basit", "beri",
                "şan", "bayım", "kardeş", "oturmak", "altı", "boyut",
                "cilt", "gökyüzü", "uyku", "yavaş yavaş", "küçük", "koku",
                "gülümsedi", "kar", "bu yüzden", "yumuşak", "toprak",
                "askerler", "çözüm", "bazı", "birisi", "bir şey", "bazen",
                "ancak", "şarkı", "yakında", "ses", "güney", "güney",
                "uzay", "konuşmak", "özel", "hız", "büyü", "ticari",
                "yayılmış", "bahar", "kare", "durmak", "yıldız", "başla",
                "devlet", "ifade", "kalmak", "çelik", "adım", "sopa",
                "yine", "taş", "Durduğu", "dur", "mağaza", "öykü", "düz",
                "garip", "dere", "sokak", "gergin", "dizi", "güçlü",
                "öğrenciler", "çalışma", "konu", "maddeler", "arama",
                "aniden", "sonek", "şeker", "önerdi", "toplam", "buzzer",
                "güneş", "besleme", "zannetmek", "emin", "yüzey",
                "sürpriz", "yüzmek", "hece", "semboller", "sistem",
                "tablo", "kuyruk", "almak", "talk", "uzun boylu",
                "öğretmen", "takım", "söylemek", "sıcaklık", "inci",
                "şartlar", "test", "göre", "yaptım", "onların", "onları",
                "onlar Kendilerini", "o zaman", "orada", "tez", "onlar",
                "kalın", "ince", "şey", "düşünmek", "üçüncü", "bu", "bu",
                "gerçi", "düşünce", "binlerce", "üç", "sayesinde",
                "Malthus", "bağlı", "zaman", "küçücük", "için (amacıyla)",
                "bugün", "birlikte", "söyledi", "ton", "çok", "aldı",
                "Araçlar", "üst", "toplam", "dokunma", "karşı", "kasaba",
                "iz", "ticaret", "tren", "seyahat", "ağaç", "üçgen",
                "gezi", "sorun", "kamyon", "gerçek", "denemek", "tüp",
                "dönüş", "iki", "sınıf", "amca", "altında",
                "altını çizmek", "anlamak", "birim", "kadar", "yukarı",
                "üzerine", "bize", "kullanımı", "genellikle", "vadi",
                "değer", "çeşitli", "fiil", "çok", "görünüm", "köy",
                "ziyaret", "ses", "ünlü", "bekle!", "yürümek", "sur",
                "istiyorum", "oldu", "sıcak", "ne", "yıkama", "Washington",
                "değildi", "izlemek", "su", "dalgalar", "aksi halde",
                "biz", "giymek", "hava durumu", "hafta", "ağırlık", "iyi",
                "yaparız", "gitti", "edildi", "batı", "batı", "ne",
                "tekerlekler", "Ne zaman", "nerede", "olup olmadığını",
                "hangi", "süre", "beyaz", "kim", "toptan", "kimin",
                "neden", "geniş", "eş", "vahşi", "istiyor", "win",
                "rüzgâr", "pencere", "kanatlar", "kış", "tel", "dilek",
                "ile", "içinde", "olmadan", "kadın", "kadın",
                "harikalar diyarı", "olmaz", "ahşap", "kelime", "iş",
                "işçiler", "dünya", "yapardın", "bunu yapmazdı", "yazmak",
                "yazılı", "yanlış", "yazdı", "yarda", "yıl", "sarı",
                "evet", "henüz", "sen", "genç", "senin", "kendiniz"},

        {"para ser capaz de", "sobre", "acima",
                "transversalmente", "ato", "ação", "na realidade",
                "adicionar", "adição", "adjetivo", "ter medo", "África",
                "ânus", "novamente", "contra", "idade", "atrás",
                "combinado", "à frente", "ar", "tudo", "permitir", "quase",
                "sozinho", "juntamente", "já", "assim", "embora", "sempre",
                "no", "América", "entre", "quantidade", "e", "ângulo",
                "animal", "outro", "resposta", "qualquer", "nada",
                "apareceu", "maçã", "são", "área", "brasão", "exército",
                "em torno de", "chegou", "tipo", "como", "perguntar", "em",
                "longe", "bebê", "de volta", "banheiro", "bola", "Banco",
                "base", "ser", "suportar", "bater", "belo", "Tornou-se",
                "porque", "tornar-se", "cama", "concluído", "antes",
                "começado", "início", "atrás", "ser", "acreditar", "sino",
                "pertencer", "abaixo", "ao lado de", "o melhor", "melhor",
                "entre", "grande", "projeto de lei", "aves", "bocado",
                "preto", "bloco", "sangue", "golpe", "azul", "conselho",
                "barco", "corpo", "ossos", "facebook", "fonte", "tanto",
                "inferior", "caixa", "menino", "ramos", "pausa",
                "brilhante", "para trazer", "britânico", "quebrado",
                "irmão", "trazido", "marrom", "construir", "edifício",
                "construído", "ardente", "negócio", "mas", "comprar",
                "por", "chamada", "veio", "lata", "não pode", "não pode",
                "capital", "capitão", "carro", "cuidado",
                "cuidar totalmente", "transportar", "caso", "gato",
                "captura", "gado", "capturados", "causa", "células",
                "centro", "centavos", "século", "certo", "chance",
                "mudança", "gráfico", "verificar", "chefe", "criança",
                "crianças", "escolher", "igreja", "círculo", "cidade",
                "classe", "limpo", "claro", "subiu", "perto", "roupa",
                "nuvem", "costa", "frio", "cor", "coluna", "vir", "comum",
                "Empresas", "comparar", "completo", "composto",
                "condições", "a considerar", "consoante", "a contenção",
                "contínuo", "controle", "cozinheiro", "legal", "cópia",
                "milho", "canto", "correto", "custo", "algodão", "poderia",
                "não podia", "contar", "país", "curso", "coberto", "vacas",
                "criar", "chorou", "culturas", "atravessar", "multidão",
                "atual", "corte", "dança", "escuro", "dia", "morto",
                "acordo", "morte", "DECIDIDO", "decimal", "profundo",
                "descrever", "deserto", "projeto", "detalhes",
                "meu determinista", "desenvolvido", "dicionário", "fez",
                "não fez", "morreu", "diferença", "diferente", "difícil",
                "direto", "direção", "descoberto", "distância", "dividido",
                "divisão", "fazer", "médico", "faz", "não faz", "cão",
                "dólares", "feito", "porta", "para baixo", "desenhar",
                "desenho", "vestido", "conduzir", "cair", "seca",
                "caindo sobre", "cada", "cedo", "orelhas", "terra",
                "leste", "fácil", "comer", "borda", "efeito", "ovos",
                "oito", "ou", "elétrico", "elementos", "outro", "fim",
                "energia", "motor", "Inglaterra", "Inglês", "desfrutar",
                "suficiente", "Introduzido", "inteiro", "igual", "equação",
                "especialmente", "Europa", "mesmo", "noite", "sempre",
                "cada", "todo o mundo", "tudo", "exatamente", "exemplo",
                "exceto", "emocionante", "exercício", "esperar",
                "experiência", "experiência", "explicar", "para expressar",
                "expressivo", "olho", "facebook", "fato", "fábricas",
                "fatores", "caso", "família", "famoso", "longe", "fazenda",
                "agricultores", "quase", "pai", "medo", "sentir",
                "sentimento", "pés", "pele", "sentido", "poucos", "campo",
                "figo", "luta", "figura", "preenchido", "finalmente",
                "lugar", "multa", "dedos", "acabado", "fogo", "cume",
                "peixe", "necessário", "cinco", "apartamento", "piso",
                "fluir", "flores", "voar", "seguir", "comida", "pé",
                "para", "força", "floresta", "forma", "para a frente",
                "encontrado", "quatro", "fração", "França", "livre",
                "francês", "fresco", "amigos", "a partir de", "frente",
                "fruto", "completo", "diversão", "jogo", "jardim", "gás",
                "deu", "geral", "obter", "menina", "dar", "vidro", "ir",
                "deus", "ouro", "desaparecido", "bom", "tem", "governo",
                "grama", "grande", "grego", "verde", "cresceu", "terreno",
                "grupo", "crescer", "adivinhar", "pistola", "teve",
                "cabelo", "justo", "mão", "aconteceu", "feliz", "difícil",
                "tem", "tem", "ter", "ei", "cabeça", "Ouça", "ouvido",
                "coração", "calor", "pesado", "herói", "ajudar", "aqui",
                "aqui", "alto", "colina", "ele", "se", "seu", "história",
                "acertar", "segurar", "buraco", "casa", "esperança",
                "cavalo", "quente", "horas", "casa", "como", "ENTRETANTO",
                "enorme", "humano", "cem", "caça", "Eu", "gelo", "idéia",
                "se", "vou", "importante", "em", "polegadas", "incluir",
                "aumentar ampliar", "Índia", "para indicar indicando",
                "indústria", "informações", "insetos", "dentro", "em vez",
                "instrumentos", "interesse", "em", "ferro", "é",
                "Islândia", "não é", "ele", "sua", "é", "se", "japonês",
                "trabalho", "ingressou", "saltado", "justo", "aguente!",
                "guardado", "chave", "assassinado", "criança", "rei",
                "sabia", "eu sei", "conhecido", "senhora", "salmoura",
                "país", "língua", "grande", "carga", "mais tarde", "riu",
                "lei", "para colocar", "para liderar", "aprender",
                "mínimo", "deixar", "LED", "esquerda", "pernas",
                "comprimento", "menos", "deixar", "vamos", "carta",
                "nível", "mentira", "vida", "levantado", "luz", "como",
                "linha", "astúcia", "lista", "pouco", "viver",
                "localizado", "longo", "olhar", "perdido", "solda", "alto",
                "amor", "baixo", "máquina", "larva", "principal", "maior",
                "fazer", "um", "muitos", "mapa", "marcha", "medula",
                "fósforo", "material", "mate", "poder", "talvez", "me",
                "significar", "medir", "carne", "atender", "melodia",
                "membros", "homens", "metal", "método", "meio",
                "pode também", "milha", "leite", "milhão", "mente", "mina",
                "minutos", "senhorita", "moderno", "moléculas", "momento",
                "dinheiro", "meses", "lua", "mais", "manhã", "necessário",
                "mãe", "montanha", "boca", "mudança", "movimento", "muito",
                "música", "necessário", "meu", "nome", "nação", "natural",
                "perto", "necessário", "necessidade", "nunca", "novo",
                "próximo", "noite", "não", "normal", "norte", "norte",
                "nariz", "aflição", "nota", "nada", "aviso", "substantivo",
                "agora", "número", "numeral", "objeto", "observar",
                "oceano", "de", "fora", "escritório", "freqüentemente",
                "ó", "óleo", "velho", "em", "uma vez", "um", "só",
                "aberto", "oposto", "ou", "ordem", "outro", "nosso",
                "fora", "fora", "sobre", "independentemente", "oxigênio",
                "página", "pintar", "par", "papel", "parágrafo", "parque",
                "parte", "em particular", "festa", "passou", "passado",
                "padrão", "pagar", "pessoas", "por", "talvez", "período",
                "pessoa", "frase", "escolhido", "quadro", "peça", "lugar",
                "planície", "avião", "lona", "planos", "plantas", "jogar",
                "por favor", "plural", "poema", "ponto", "pólo", "pobre",
                "posição", "possível", "libras", "poder", "prática",
                "preparado", "presidentes", "bastante", "impresso",
                "provavelmente", "problema", "processo", "para produzir",
                "comestíveis", "propriedade", "para fornecer", "puxado",
                "empurrado", "colocar", "perguntas", "rapidamente",
                "calma", "bastante", "corrida", "rádio", "chuva",
                "levantado", "ran", "mais", "alcançado", "ler", "pronto",
                "realmente", "razão", "recebido", "registro", "vermelho",
                "região", "REMAIN", "lembrar", "repetido", "relatório",
                "representar", "ressentir", "residual", "resultado",
                "retorno", "ritmo", "rico", "a andar", "direito", "anel",
                "subir", "rio", "estrada", "rocha", "enrolado", "quarto",
                "raiz", "corda", "rosa", "volta", "linha", "regra",
                "executar", "seguro", "dito", "vela", "semente", "areia",
                "para se sentar", "para salvar", "serra", "dizer",
                "escala", "escola", "ciência", "cientistas", "contagem",
                "mar", "assento", "segundo", "seção", "lago", "sementes",
                "PARECEM", "lagos", "companhia", "enviar", "gadanha",
                "enviado", "sentença", "separado", "servir", "conjunto",
                "estabelecido", "sete", "vários", "Shall", "forma",
                "forte", "ela", "navio", "sapatos", "loja", "curto",
                "shoulderstand", "ombro", "gritou", "exposição",
                "mostrado", "lado", "vista", "sinal", "sinal",
                "silencioso", "similar", "simples", "desde", "de canto",
                "senhor", "irmã", "sentar-se", "seis", "tamanho", "pele",
                "céu", "sono", "lentamente", "pequeno", "cheiro", "sorriu",
                "neve", "assim", "suave", "solo", "soldados", "solução",
                "alguns", "alguém", "algo", "às vezes", "mas", "canção",
                "em breve", "parecer", "sul", "meridional", "espaço",
                "falar", "especial", "velocidade", "soletrar", "comercial",
                "propagação", "primavera", "quadrado", "suporte",
                "estrelas", "início", "estado", "afirmação", "ficar",
                "aço", "passo", "vara", "ainda", "pedra", "Parou", "Pare",
                "loja", "história", "em linha reta", "estranho", "córrego",
                "rua", "esticada", "corda", "forte", "estudantes",
                "estudo", "assunto", "substâncias", "pesquisa",
                "de repente", "sufixo", "açúcar", "sugerido", "soma",
                "cigarra", "sol", "fornecimento", "supor", "certo",
                "superfície", "surpresa", "natação", "sílabas", "símbolos",
                "sistema", "mesa", "cauda", "tomar", "talco", "alto",
                "professor", "equipe", "dizer", "temperatura", "º",
                "condições", "teste", "que", "fez", "seu", "eles",
                "eles Mesmos", "depois", "lá", "tese", "eles", "grosso",
                "fino", "coisa", "pensar", "terceiro", "este", "aqueles",
                "embora", "pensamento", "Milhares", "três", "através",
                "Malthus", "amarrado", "tempo", "minúsculo", "a (para)",
                "hoje", "juntos", "disse", "tom", "também", "levou",
                "ferramentas", "topo", "total", "toque", "para", "cidade",
                "caminho", "comércio", "trem", "viagem", "árvore",
                "triângulo", "viagem", "dificuldade", "caminhão",
                "verdadeiro", "tentar", "tubo", "vez", "dois", "grau",
                "tio", "em", "sublinhar", "entender", "unidade", "até",
                "para cima", "sobre", "nós", "usar", "geralmente", "vale",
                "valor", "vário", "verbo", "muito", "vista", "aldeia",
                "visita", "voz", "vogal", "espere!", "andar", "baluarte",
                "querer", "foi", "quente", "o que", "lavagem",
                "Washington", "não estava", "observar", "água", "ondas",
                "caso contrário", "nós", "desgaste", "tempo", "semana",
                "peso", "bem", "nós vamos", "fui", "foram", "oeste",
                "ocidental", "o que", "rodas", "quando", "onde", "se",
                "que", "enquanto", "branco", "que", "por grosso",
                "de quem", "por que", "grande", "esposa", "selvagem",
                "quer", "ganhar", "vento", "janela", "asas", "inverno",
                "arame", "desejo", "com", "dentro", "sem", "mulher",
                "mulheres", "país das maravilhas", "não vai", "madeira",
                "palavra", "trabalho", "trabalhadores", "mundo",
                "faria isso", "não faria isso", "escrever", "escrito",
                "errado", "escreveu", "quintal", "ano", "amarelo", "sim",
                "ainda", "você", "jovem", "seu", "você mesmo"},
        {"щоб мати можливість", "про", "вище", "через", "акт",
                "дію", "насправді", "додавати", "додаток", "прикметник",
                "боятися", "Африка", "анус", "знову", "проти", "вік",
                "тому", "вирішено", "вперед", "повітря", "всі",
                "дозволяти", "майже", "один", "разом", "вже", "так",
                "хоча", "завжди", "в", "Америка", "серед", "кількість",
                "і", "кут", "тварина", "другий", "відповідь", "будь",
                "всі", "з'явився", "яблуко", "є", "площа", "зброю",
                "армія", "навколо", "прибулий", "тип", "як", "просити",
                "в", "далеко", "дитина", "назад", "ванна кімната", "м'яч",
                "банк", "база", "бути", "нести", "бити", "красивий",
                "став", "тому що", "ставати", "ліжко", "завершено", "до",
                "почав", "починати", "за", "є", "вірити", "дзвін",
                "належати", "нижче", "поруч", "кращий", "краще", "між",
                "великий", "законопроект", "птиці", "біт", "чорний",
                "блок", "кров", "удар", "синій", "дошка", "човен", "тіло",
                "кістки", "facebook", "джерело", "обидва", "дно",
                "коробка", "хлопчик", "філії", "перерву", "яскравий",
                "довести", "британський", "зламаний", "брат", "притягнуто",
                "коричневий", "будувати", "будівля", "побудований",
                "спалювання", "бізнес", "але", "купити", "по", "виклик",
                "прийшов", "може", "не можу", "не можу", "капітал",
                "капітан", "автомобіль", "догляд", "піклуватися повністю",
                "нести", "справа", "кішка", "улов", "велика рогата худоба",
                "спійманий", "причина", "клітини", "центр", "центів",
                "повік", "певний", "шанс", "зміна", "діаграма",
                "перевіряти", "головний", "дитина", "діти", "вибирати",
                "церква", "коло", "Сіті", "клас", "чистий", "ясно",
                "піднявся", "близько", "одяг", "хмара", "узбережжі",
                "холодний", "колір", "колонка", "приїхати", "загальний",
                "компанії", "порівняти", "повний", "з'єднання",
                "обстановка", "для розгляду", "приголосний", "стримуванню",
                "продовжував", "контроль", "кухар", "прохолодно", "копія",
                "кукурудза", "кут", "вірний", "вартість", "бавовна",
                "може", "не міг", "вважати", "країна", "курс", "покритий",
                "корови", "створювати", "плакав", "зернові", "хрест",
                "натовп", "струм", "вирізати", "танець", "темно", "день",
                "мертвий", "угода", "смерть", "ВИРІШИЛИ", "десятковий",
                "глибоко", "описувати", "пустеля", "дизайн", "деталі",
                "детермінований шахта", "розвиненою", "словник", "зробив",
                "зробив не", "помер", "різниця", "другий", "важкий",
                "прямий", "напрямок", "виявлений", "відстань",
                "розділений", "поділ", "робити", "лікар", "робить", "НЕ",
                "собака", "доларів", "зроблений", "двері", "вниз",
                "малювати", "малюнок", "плаття", "привід", "падіння",
                "сухий", "падіння на", "кожен", "рано", "вушка", "земля",
                "схід", "легко", "є", "край", "ефект", "яйця", "вісім",
                "або", "електричний", "елементи", "ще", "кінець",
                "енергія", "двигун", "Англія", "англійська",
                "насолоджуватися", "досить", "вступив", "весь", "рівний",
                "рівняння", "особливо", "Європа", "навіть", "вечір",
                "коли-небудь", "кожен", "всі", "всі", "точно", "приклад",
                "крім", "захоплюючий", "вправа", "очікувати", "досвід",
                "експеримент", "пояснювати", "висловити", "виразний",
                "очей", "facebook", "факт", "заводи", "фактори", "справа",
                "сім'я", "відомий", "далеко", "ферма", "фермери", "майже",
                "батько", "страх", "відчувати", "почуття", "ноги", "хутро",
                "повсть", "кілька", "поле", "інжир", "боротьба", "фігура",
                "заповнений", "зрештою", "місце", "відмінно", "пальці",
                "закінчений", "вогонь", "хребет", "риба", "необхідний",
                "п'ять", "квартира", "поверх", "текти", "квіти", "літати",
                "слідувати", "їжа", "фут", "для", "сила", "ліс", "форма",
                "вперед", "знайдено", "чотири", "частка", "Франція",
                "безкоштовно", "французький", "свіжий", "друзі", "від",
                "фронт", "фрукти", "повний", "веселощі", "гра", "сад",
                "газ", "дав", "загальний", "отримувати", "дівчина",
                "давати", "скло", "йти", "Бог", "золото", "пішов", "добре",
                "отримав", "уряд", "трава", "великий", "грецький",
                "зелений", "виросла", "земля", "група", "зростати",
                "здогадуватися", "пістолет", "було", "волосся", "просто",
                "рука", "відбулося", "щасливий", "жорсткий", "має", "має",
                "мати", "агов", "керівник", "Слухайте", "чув", "серце",
                "тепло", "важкий", "герой", "допомога", "тут", "тут",
                "високий", "пагорб", "його", "сам", "його", "історія",
                "хіт", "тримати", "отвір", "додому", "сподіватися", "кінь",
                "гарячий", "годин", "будинок", "як", "ОДНАК", "величезний",
                "гуманний", "сто", "полювання", "Я", "лід", "ідея", "якщо",
                "Я буду", "важливий", "в", "дюймів", "включати",
                "збільшити Збільшити", "Індія", ", щоб вказати, що вказує",
                "промисловість", "інформація", "комахи", "всередині",
                "замість", "інструменти", "інтерес", "в", "залізо", "є",
                "Ісландія", "хіба це не", "це", "його", "це", "сам",
                "Японський", "робота", "приєднався", "підскочили",
                "просто", "тримайся!", "збережений", "ключ", "вбитий",
                "дитина", "король", "знав", "Я знаю,", "відомий", "леді",
                "розсіл", "країна", "мову", "великий", "навантаження",
                "пізніше", "сміялися", "закон", "закласти", "вести",
                "вчитися", "як мінімум", "залишати", "призвело", "зліва",
                "ноги", "довжина", "менше", "дозволяти", "давайте", "лист",
                "рівень", "брехня", "життя", "піднятий", "світло",
                "подібно", "лінія", "хитрість", "список", "трохи", "жити",
                "розташований", "довго", "дивитися", "втрачений", "припой",
                "голосно", "любов", "низький", "машина", "личинка",
                "основний", "основний", "робити", "один", "багато",
                "карта", "марш", "мозок", "матч", "матеріал", "матовий",
                "може", "може бути", "мене", "означати", "вимірювати",
                "м'ясо", "задоволення", "мелодія", "члени", "люди",
                "метал", "метод", "середній", "також можуть", "милі",
                "молоко", "мільйон", "розум", "шахта", "хвилин", "міс",
                "сучасний", "молекули", "момент", "гроші", "місяців",
                "місяць", "більш", "ранок", "повинен", "мати", "гора",
                "рот", "рух", "рух", "багато", "музика", "повинен", "мій",
                "назва", "нація", "природний", "близько", "необхідно",
                "потребувати", "ніколи", "новий", "наступний", "ніч",
                "немає", "нормальний", "на північ", "північний", "ніс",
                "дистрес", "примітка", "нічого", "сповіщення", "іменник",
                "зараз", "число", "цифра", "об'єкт", "спостерігати",
                "океан", "з", "від", "офіс", "часто", "ой", "масло",
                "старий", "на", "один раз", "один", "тільки", "відкритий",
                "навпроти", "або", "порядок", "другий", "наш", "з", "поза",
                "над", "незалежно", "кисень", "сторінка", "фарба", "пара",
                "папір", "пункт", "парк", "частина", "зокрема", "партія",
                "пройшло", "мимо", "шаблон", "платити", "люди", "по",
                "можливо", "період", "людина", "фраза", "взяв", "картинка",
                "шматок", "місце", "рівнини", "літак", "брезент", "плани",
                "рослини", "грати", "будь ласка", "множина", "вірш",
                "точка", "поляк", "бідний", "положення", "можливе",
                "фунти", "потужність", "практика", "підготовлений",
                "президенти", "досить", "друкований", "ймовірно",
                "проблема", "процес", "виробляти", "бакалійні товари",
                "майно", "щоб забезпечити", "витягнув", "штовхнув",
                "ставити", "питання", "швидко", "тихо", "цілком", "гонка",
                "радіо", "дощ", "піднятий", "побіг", "швидше", "досяг",
                "читати", "готовий", "дійсно", "причина", "отримано",
                "запис", "червоний", "область", "ЗАЛИШАТИСЯ",
                "запам'ятати", "повторний", "звіт", "представляти",
                "обурюватися", "залишковий", "результат", "повернення",
                "ритм", "багаті", "їздити", "право", "кільце",
                "підніматися", "річка", "дорога", "рок", "прокат", "номер",
                "корінь", "мотузка", "Роуз", "круглий", "рядок", "правило",
                "запустити", "сейф", "зазначений", "вітрило", "насіння",
                "пісок", "сидіти", "зберегти", "пила", "сказати", "шкала",
                "школа", "наука", "вчені", "рахунок", "море", "сидіння",
                "другий", "розділ", "озеро", "насіння", "SEEM", "озера",
                "компанія", "послати", "коса", "посланий", "вирок",
                "окремий", "служити", "набір", "оселилися", "сім",
                "кілька", "доведи", "форма", "гострий", "вона", "корабель",
                "взуття", "магазин", "короткий", "на плечах", "плече",
                "кричав", "шоу", "показаний", "сторона", "зір", "знак",
                "сигнал", "тихий", "аналогічний", "простий", "з", "спів",
                "сер", "сестра", "сидіти", "шість", "розмір", "шкіра",
                "небо", "сон", "повільно", "невеликої", "нюх",
                "посміхнувся", "сніг", "так", "м'який", "грунт", "солдати",
                "рішення", "деякі", "хтось", "щось", "іноді", "але",
                "пісня", "скоро", "звук", "південь", "південний",
                "простір", "говорити", "спеціальний", "швидкість",
                "заклинання", "комерційний", "поширення", "весна", "площа",
                "стояти", "зірки", "починати", "держава", "заяву",
                "залишатися", "сталь", "крок", "палиця", "ще", "камінь",
                "стояв", "зупинити", "магазин", "історія", "прямо",
                "дивний", "потік", "вулиця", "розтягується", "рядок",
                "сильний", "студенти", "дослідження", "тема", "речовини",
                "пошук", "раптом", "суфікс", "цукор", "запропонований",
                "сума", "зумер", "сонце", "поставка", "припускати",
                "звичайно", "поверхню", "сюрприз", "плавати", "склади",
                "символи", "система", "стіл", "хвіст", "приймати", "тальк",
                "високий", "вчитель", "команда", "сказати", "температура",
                "ї", "умови", "тест", "ніж", "зробив", "їх", "їх",
                "вони самі", "потім", "там", "тезу", "вони", "товстий",
                "тонкий", "річ", "думати", "третій", "це", "ті", "хоча",
                "думка", "тисячі", "три", "через", "Мальтус", "пов'язаний",
                "час", "крихітний", "щоб (для того, щоб)", "сьогодні",
                "разом", "сказав", "тон", "занадто", "взяв",
                "інструментарій", "топ", "загальний", "торкнутися", "до",
                "місто", "трек", "торгівля", "поїзд", "подорож", "дерево",
                "трикутник", "поїздка", "біда", "вантажівка", "правда",
                "намагатися", "трубка", "поворот", "два", "клас", "дядько",
                "під", "підкреслення", "зрозуміти", "блок", "до", "вгору",
                "на", "нам", "використовувати", "зазвичай", "долина",
                "значення", "різний", "дієслово", "дуже", "вид", "село",
                "візит", "голос", "гласний", "чекати!", "ходити", "вал",
                "хотіти", "було", "теплий", "що", "мити", "Вашингтон",
                "не було", "дивитися", "води", "хвилі", "в іншому випадку",
                "ми", "носити", "погода", "тиждень", "вага", "добре",
                "ми будемо", "пішов", "були", "захід", "західний", "що",
                "колеса", "коли", "де", "Лі", "який", "в той час як",
                "білий", "хто", "оптова торгівля", "чиї", "чому",
                "широкий", "дружина", "дикий", "хоче", "виграти", "вітер",
                "вікно", "крила", "зима", "провід", "бажання", "з", "в",
                "без", "жінка", "жінки", "країна чудес", "НЕ БУДЕ",
                "дерево", "слово", "робота", "робочі", "світ",
                "зробив би це", "не зробив би цього", "запис", "написаний",
                "неправильно", "писав", "двір", "рік", "жовтий", "да",
                "ще", "ви", "молодий", "ваш", "себе"},
        {"لتكون قادرة", "حول", "فوق", "عبر", "فعل", "عمل",
                "في الواقع", "إضافة", "إضافة", "نعت", "لتخافوا", "أفريقيا",
                "بعد", "ثانية", "ضد", "سن", "منذ", "متفق عليه", "قدما",
                "هواء", "كل", "السماح", "تقريبا", "وحده", "على طول",
                "سابقا", "أيضا", "رغم أن", "دائما", "صباحا", "أمريكا",
                "بين", "مبلغ", "و", "زاوية", "حيوان", "آخر", "إجابة", "أي",
                "أي شئ", "ظهرت", "تفاحة", "و", "منطقة", "أسلحة", "جيش",
                "حول", "وصل", "فن", "كما", "تطلب", "في", "بعيدا", "طفل",
                "ظهر", "سيئة", "كرة", "مصرف", "قاعدة", "يكون", "تحمل",
                "فاز", "جميل", "أصبح", "ل", "أصبح", "قاع", "كان", "قبل",
                "بدأ", "بدأ", "وراء", "يجري", "اعتقد", "جرس", "تنتمي",
                "أقل من", "بجانب", "أفضل", "أفضل", "بين", "كبير",
                "مشروع قانون", "الطيور", "لقمة", "أسود", "كتلة", "دم",
                "ضربة", "أزرق", "مجلس", "قارب", "هيئة", "العظام", "كتاب",
                "مولود", "كلا", "أسفل", "صندوق", "صبي", "الفروع",
                "استراحة", "مشرق", "لجلب", "البريطانيون", "كسر", "شقيق",
                "جلبت", "أسمر", "بناء", "بناء", "بني", "إحراق", "عمل",
                "لكن", "شراء", "من قبل", "دعوة", "جاء", "علبة", "لا يمكن",
                "لا يمكن", "عاصمة", "نقيب", "سيارة", "رعاية", "بعناية",
                "حمل", "حالة", "قط", "مزلاج", "ماشية", "اشتعلت", "سبب",
                "الخلايا", "مركز", "سنتا", "قرن", "معين", "فرصة", "تغيير",
                "جدول", "تحقق", "رئيس", "طفل", "الأطفال", "اختار", "كنيسة",
                "دائرة", "مدينة", "فئة", "نظيف", "واضح", "قفز", "قريب",
                "ملابس", "سحابة", "ساحل", "بارد", "لون", "عمود", "جاء",
                "مشترك", "شركة", "مقارنة", "كامل", "مركب", "الشروط",
                "للنظر في", "متوافق", "لاحتواء", "واصل", "مراقبة", "طبخ",
                "بارد", "نسخة", "ذرة", "ركن", "صحيح", "كلفة", "قطن",
                "يمكن", "لم أستطع", "عد", "بلد", "مسار", "مغطى", "الأبقار",
                "خلق", "بكى", "المحاصيل", "عبر", "الجماهير", "حالي", "قطع",
                "رقص", "مظلم", "يوم", "ميت", "صفقة", "الموت", "قررت",
                "عشري", "عميق", "وصف", "صحراء", "تصميم", "تفاصيل", "حدد",
                "المتقدمة", "قاموس", "لم", "لم", "توفي", "فرق", "مختلف",
                "صعب", "مباشر", "اتجاه", "مكتشف", "مسافة", "منقسم",
                "تقسيم", "فعل", "الطبيب", "لا", "لا", "الكلب", "دولار",
                "منجز", "باب", "إلى", "رسم", "رسم", "فستان", "حملة",
                "قطرة", "جاف", "خلال", "كل", "في وقت مبكر", "سمع", "أرض",
                "شرق", "سهل", "أكل", "حافة", "تأثير", "بيض", "ثمانية",
                "كل", "كهربائي", "عناصر", "آخر", "نهاية", "طاقة", "محرك",
                "انجلترا", "الإنجليزية", "استمتع", "كاف", "دخلت", "كامل",
                "متساو", "معادلة", "خاصة", "أوروبا", "حتى", "مساء", "أبدا",
                "كل", "كل شخص", "كل شىء", "بالضبط", "مثال", "إلا", "مثير",
                "ممارسة", "توقع", "تجربة", "تجربة", "شرح", "للتعبير عن",
                "معبر", "عين", "وجه", "حقيقة", "المصانع", "العوامل", "سقط",
                "عائلة", "مشهور", "بعيدا", "مزرعة", "المزارعين", "سريع",
                "الأب", "خوف", "إحساس", "شعور", "قدم", "سقط", "شعر",
                "قليل", "حقل", "تين", "شجار", "شخصية", "معبأ", "أخيرا",
                "اكتشاف", "غرامة", "الأصابع", "منتهي", "حريق", "الأول",
                "سمك", "حاجة", "خمسة", "شقة", "أرضية", "تدفق", "الزهور",
                "ذبابة", "تابع", "غذاء", "قدم", "إلى", "قوة", "غابة",
                "شكل", "إلى الأمام", "أسس", "أربعة", "جزء", "فرنسا", "حر",
                "فرنسي", "جديد", "أصدقاء", "من", "جبهة", "فاكهة", "كامل",
                "مرح", "لعبة", "حديقة", "غاز", "أعطى", "عام", "الحصول على",
                "فتاة", "منح", "زجاج", "تذهب", "الله", "الذهب", "ذهب",
                "جيد", "حصلت", "حكومة", "عشب", "عظيم", "اللغة اليونانية",
                "أخضر", "نما", "أرض", "مجموعة", "تنمو", "تخمين", "بندقية",
                "كان", "شعر", "توقف", "يد", "حدث", "سعيد", "شاق", "لديه",
                "قبعة", "ديك", "هو", "رئيس", "سمع", "سمعت", "قلب", "حرارة",
                "ثقيل", "عقدت", "مساعدة", "لها", "هنا", "ارتفاع", "تل",
                "له", "نفسه", "له", "تاريخ", "ضرب", "عقد", "حفرة", "منزل",
                "أمل", "حصان", "حار", "ساعات", "منزل", "كيف", "لكن", "ضخم",
                "بشري", "مائة", "الصيد", "أنا", "جليد", "فكرة", "إذا",
                "وسوف أكون", "مهم", "في", "بوصة", "تضمن", "زيادة", "الهند",
                "للإشارة", "صناعة", "معلومات", "الحشرات", "داخل",
                "بدلا من", "الصكوك", "مصلحة", "إلى", "حديد", "هو", "جزيرة",
                "ليس", "هو", "لها", "انها", "نفسها", "اليابانية", "وظيفة",
                "انضم", "قفز", "فقط", "عقد على!", "أبقى", "مفتاح", "قتل",
                "نوع", "ملك", "عرف", "وأنا أعلم", "معروف", "سيدة", "بحيرة",
                "أرض", "لغة", "كبير", "آخر", "فيما بعد", "ضحك", "القانون",
                "لوضع", "لقيادة", "تعلم", "أدنى", "ترك", "أدى", "اليسار",
                "الساقين", "طول", "أقل", "سمح", "دعونا", "رسالة", "مستوى",
                "كذبة", "حياة", "رفعت", "ضوء", "مثل", "خط", "قائمة",
                "استمع", "القليل", "حي", "تقع", "طويل", "بحث", "مفقود",
                "الكثير", "عال", "الحب", "منخفض", "آلة", "مصنوع", "رئيسي",
                "رئيسي", "جعل", "رجل", "كثير", "خريطة", "مسيرة", "علامة",
                "مباراة", "مادة", "مسألة", "قد", "ربما", "أنا", "متوسط",
                "قياس", "لحم", "تلبية", "لحن", "أعضاء", "الرجال", "معدن",
                "طريقة", "وسط", "ربما", "ميل", "حليب", "مليون", "عقل",
                "منجم", "دقيقة", "ملكة جمال", "حديث", "جزيئات", "لحظة",
                "نقود", "أشهر", "ضوء القمر", "أكثر", "صباح", "معظم", "أم",
                "جبل", "فم", "خطوة", "حركة", "كثيرا", "موسيقى", "يجب",
                "لي", "اسم", "دولة", "طبيعي", "قرب", "ضروري", "حاجة",
                "أبدا", "جديد", "التالي", "ليل", "لا", "ولا", "شمال",
                "شمالي", "أنف", "ليس", "مذكرة", "لا شيء", "إشعار", "إسم",
                "الآن", "عدد", "عددي", "موضوع", "رصد", "المحيط", "من",
                "بعيدا", "مكتب", "غالبا", "يا", "زيت", "قديم", "في", "مرة",
                "واحد", "فقط", "فتح", "معاكس", "أو", "النظام", "آخر",
                "لنا", "خارج", "خارج", "خلال", "بشكل مستقل", "أكسجين",
                "صفحة", "طلاء", "زوج", "ورقة", "فقرة", "موقف", "جزء",
                "بخاصة", "حزب", "مرت", "الماضي", "نمط", "دفع", "الناس",
                "لكل", "ربما", "فترة", "شخص", "العبارة", "التقطت", "صور",
                "قطعة", "مكان", "السهول", "خطة", "طائرة", "مصنع",
                "النباتات", "للعب", "من فضلك", "صيغة الجمع", "قصيدة",
                "نقطة", "القطب", "فقير", "موقف", "ممكن", "جنيه", "قوة",
                "ممارسة", "معد", "الرؤساء", "جميل", "المطبوعة", "ربما",
                "مشكلة", "عملية", "لإنتاج", "البقالة", "ممتلكات", "لتوفير",
                "سحبت", "دفعت", "وضع", "الأسئلة", "بسرعة", "هادئ", "تماما",
                "سباق", "راديو", "مطر", "أثار", "ركض", "بالأحرى", "وصلت",
                "قرأ", "استعداد", "حقا", "سبب", "تلقى", "سجل", "أحمر",
                "منطقة", "بقي", "تذكر", "متكرر", "تقرير", "مثل", "استاء",
                "بقية", "نتيجة", "عودة", "إيقاع", "غني", "لركوب", "حق",
                "حلقة", "ارتفاع", "نهر", "طريق", "صخرة", "توالت", "غرفة",
                "جذر", "حبل", "ردة", "جولة", "صف", "حكم", "تشغيل", "آمن",
                "قال", "الشراع", "نفسه", "رمل", "الجلوس", "لإنقاذ",
                "منشار", "قول", "جدول", "مدرسة", "علم", "العلماء", "نتيجة",
                "بحر", "مقعد", "ثان", "قسم", "شاهد", "البذور", "بدا",
                "ينظر", "بيع", "إرسال", "إحساس", "أرسلت", "عقوبة", "مستقل",
                "خدمة", "مجموعة", "مستقر", "سبعة", "عدة", "سوف", "شكل",
                "حاد", "هي", "سفينة", "أحذية", "متجر", "قصير", "ينبغي",
                "كتف", "صاح", "عرض", "أظهرت", "جانب", "مشهد", "علامة",
                "إشارة", "صامت", "مماثل", "بسيط", "منذ", "غنى", "سيدي",
                "شقيقة", "جلس", "ستة", "حجم", "جلد", "سماء", "نوم", "ببطء",
                "صغير", "رائحة", "ابتسم", "ثلج", "هكذا", "ناعم", "تربة",
                "جنود", "حل", "بعض", "شخص ما", "شيء", "أحيانا", "ابن",
                "أغنية", "قريبا", "صوت", "جنوب", "جنوبي", "الفضاء", "تحدث",
                "خاص", "السرعة", "تهجى", "بقعة", "انتشار", "ربيع", "مربع",
                "موقف", "نجوم", "بداية", "دولة", "بيان", "إقامة", "فولاذ",
                "خطوة", "عصا", "لا يزال", "حجر", "وقف", "توقف", "متجر",
                "قصة", "مباشرة", "غريب", "تيار", "شارع", "امتدت", "سلسلة",
                "قوي", "الطلاب", "دراسة", "موضوع", "المواد", "مثل", "فجأة",
                "لاحقة", "سكر", "اقترح", "مجموع", "الصيف", "شمس", "تزويد",
                "افترض", "بالتأكيد", "سطح", "مفاجأة", "سباحة", "المقاطع",
                "رموز", "نظام", "جدول", "ذيل", "أخذ", "حديث", "طويل",
                "معلم", "فريق", "اقول", "درجة الحرارة", "عشرة", "حيث",
                "اختبار", "من", "أن", "هم", "هم", "هم أنفسهم", "ثم",
                "هناك", "هؤلاء", "هم", "سميك", "رقيق", "شيء", "اعتقد",
                "ثالث", "هذا", "هؤلاء", "رغم أن", "الفكر", "الآلاف",
                "ثلاثة", "من خلال", "وبالتالي", "مربوط", "وقت", "صغير",
                "ل(من أجل)", "اليوم", "معا", "قال", "نغمة", "أيضا",
                "استغرق", "أدوات", "أعلى", "مجموع", "لمس", "نحو", "مدينة",
                "مسار", "تجارة", "قطار", "سفر", "شجرة", "مثلث", "رحلة",
                "مشكلة", "شاحنة", "صحيح", "محاولة", "أنبوب", "منعطف",
                "اثنان", "نوع", "عم", "تحت", "أكد", "فهم", "وحدة", "حتى",
                "فوق", "على", "لنا", "لاستخدام", "عادة", "واد", "قيمة",
                "مختلف", "الفعل", "جدا", "رأي", "قرية", "زيارة", "صوت",
                "حرف لين", "الانتظار!", "سير", "جدار", "تريد", "حرب",
                "دافئ", "كان", "غسل", "واشنطن", "لم يكن", "راقب", "ماء",
                "أمواج", "وإلا", "نحن", "ارتداء", "طقس", "أسبوع", "الوزن",
                "جيد", "سنقوم", "ذهب", "و", "غرب", "الغربي", "ما", "عجلات",
                "عندما", "حيث", "سواء", "التي", "في حين", "أبيض", "الذي",
                "كامل", "الذي", "لماذا", "واسع", "زوجة", "بري", "سوف",
                "الفوز", "رياح", "نافذة", "أجنحة", "شتاء", "الأسلاك",
                "رغب", "مع", "ضمن", "بدون", "امرأة", "نساء", "عجب",
                "سوف لا", "خشب", "كلمة", "عمل", "العمال", "عالم",
                "سيفعل ذلك", "لن تفعل ذلك", "إرسال", "مكتوب", "خاطئ",
                "كتب", "ساحة", "عام", "أصفر", "نعم", "بعد", "أنت", "شاب",
                "ك", "نفسك"},

        {"kuwa na uwezo wa", "kuhusu", "juu ya", "katika",
                "tendo", "hatua", "kweli", "kuongeza", "Aidha",
                "adjective", "kuwa na hofu", "Afrika",
                "njia ya haja kubwa", "tena", "dhidi ya", "umri",
                "iliyopita", "walikubaliana", "mbele", "hewa", "wote",
                "kuruhusu", "karibu", "peke yake", "pamoja", "tayari",
                "hivyo", "Ingawa", "daima", "katika", "Amerika ya",
                "kati ya", "kiasi", "na", "angle", "mnyama", "mwingine",
                "jibu", "yoyote", "kitu chochote", "alionekana", "apple",
                "ni", "eneo", "silaha", "jeshi", "karibu", "aliwasili",
                "aina", "kama", "kuuliza", "katika", "mbali", "mtoto",
                "nyuma", "bafuni", "mpira", "benki ya", "msingi", "kuwa",
                "kubeba", "kuwapiga", "nzuri", "akawa", "kwa sababu",
                "kuwa", "kitanda", "kukamilika", "kabla ya", "kuanza",
                "kuanza", "nyuma ya", "kuwa", "kuamini", "kengele", "ni",
                "chini ya", "kando ya", "bora", "bora", "katika kati ya",
                "kubwa", "muswada", "ndege", "kidogo", "nyeusi", "kuzuia",
                "damu", "pigo", "bluu", "bodi", "mashua", "mwili",
                "mifupa", "facebook", "fount", "wote", "chini", "sanduku",
                "mvulana", "matawi", "mapumziko", "mkali", "kuleta",
                "Uingereza", "kuvunjwa", "ndugu", "kuletwa", "brown",
                "kujenga", "jengo", "kujengwa", "kuungua", "biashara",
                "lakini", "kununua", "na", "wito", "alikuja", "unaweza",
                "hawawezi", "hawawezi", "mji mkuu wa", "nahodha", "gari",
                "huduma", "huduma kikamilifu", "kubeba", "kesi", "paka",
                "catch", "ng'ombe", "hawakupata", "sababu", "seli",
                "kituo cha", "senti", "karne ya", "baadhi ya", "nafasi",
                "mabadiliko ya", "chati", "kuangalia", "wakuu", "mtoto",
                "watoto", "kuchagua", "kanisa", "mzunguko", "mji",
                "darasa", "safi", "wazi", "akapanda", "karibu", "nguo",
                "wingu", "pwani", "baridi", "rangi", "safu", "kuja",
                "kawaida", "makampuni ya", "kulinganisha", "kamili",
                "eneo", "hali ya", "kwa Fikiria", "consonant",
                "kwa containment", "kuendelea", "kudhibiti", "mpishi",
                "baridi", "nakala", "nafaka", "kona", "sahihi", "gharama",
                "pamba", "inaweza", "hawakuweza", "kuhesabu", "nchi",
                "Bila shaka", "kufunikwa", "ng'ombe", "kujenga", "kelele",
                "mazao", "kuvuka", "umati wa watu", "sasa", "kata",
                "ngoma", "giza", "siku", "wafu", "mpango", "kifo",
                "aliamua", "decimal", "kina", "kuelezea", "jangwa",
                "kubuni", "maelezo", "deterministic yangu",
                "zilizoendelea", "kamusi", "alifanya", "hakuwa", "alikufa",
                "tofauti", "mbalimbali", "vigumu", "moja kwa moja",
                "mwelekeo", "kugundua", "mbali", "kugawanywa",
                "mgawanyiko", "kufanya", "daktari", "gani", "haina",
                "mbwa", "dola", "done", "mlango", "chini", "kuteka",
                "kuchora", "mavazi", "gari", "tone", "kavu",
                "kuanguka juu ya", "kila", "mapema", "masikio", "nchi",
                "mashariki", "rahisi", "kula", "makali", "athari", "mayai",
                "nane", "ama", "umeme", "mambo", "mwingine", "mwisho",
                "nishati", "injini", "England", "English", "kufurahia",
                "kutosha", "Aliingia", "nzima", "sawa", "equation", "hasa",
                "Ulaya", "hata", "jioni", "milele", "kila", "kila mtu",
                "kila kitu", "hasa", "mfano", "ila", "kusisimua", "zoezi",
                "kutarajia", "uzoefu", "majaribio", "kueleza", "kueleza",
                "expressive", "jicho", "facebook", "ukweli", "viwanda",
                "sababu", "kesi", "familia", "maarufu", "mbali", "shamba",
                "wakulima", "karibu", "baba", "hofu", "kujisikia", "hisia",
                "miguu", "manyoya", "waliona", "chache", "shamba", "mtini",
                "kupambana", "takwimu", "kujazwa", "hatimaye", "mahali",
                "faini", "vidole", "kumaliza", "moto", "ridge", "samaki",
                "inahitajika", "tano", "gorofa", "sakafu", "kati", "maua",
                "kuruka", "kufuata", "chakula", "mguu", "kwa", "nguvu",
                "msitu", "fomu", "mbele", "kupatikana", "nne", "sehemu",
                "Ufaransa", "bure", "Kifaransa", "safi", "rafiki",
                "kutoka", "mbele", "matunda", "full", "furaha", "mchezo",
                "bustani", "gesi", "alitoa", "ujumla", "kupata",
                "msichana", "kutoa", "kioo", "kwenda", "Mungu", "dhahabu",
                "gone", "nzuri", "got", "serikali", "nyasi", "kubwa",
                "Kigiriki", "kijani", "ilikua", "ardhi", "kundi", "kukua",
                "nadhani", "bunduki", "alikuwa", "nywele", "tu", "mkono",
                "kilichotokea", "furaha", "ngumu", "ina", "ina", "na",
                "hey", "kichwa", "kusikia", "habari", "moyo", "joto",
                "nzito", "shujaa", "msaada", "hapa", "hapa", "high",
                "kilima", "naye", "mwenyewe", "yake", "historia", "hit",
                "kushikilia", "shimo", "nyumbani", "matumaini", "farasi",
                "moto", "masaa", "nyumba", "jinsi", "ISIPOKUWA", "mkubwa",
                "awali", "mia", "uwindaji", "mimi", "barafu", "wazo",
                "kama", "mimi itabidi", "muhimu", "katika", "inches",
                "ni pamoja na", "kuongeza Kurefusha", "India",
                "zinaonyesha kuonyesha", "sekta ya", "habari", "wadudu",
                "ndani ya", "badala", "vyombo", "maslahi", "ndani ya",
                "chuma", "ni", "Iceland", "Je, si", "ni", "yake", "ni",
                "yenyewe", "Japan", "kazi", "alijiunga na", "akaruka",
                "tu", "kushikilia!", "naendelea", "muhimu", "kuuawa",
                "mtoto", "mfalme", "alijua", "mimi najua", "inayojulikana",
                "mwanamke", "brine", "nchi", "lugha", "kubwa", "mzigo",
                "baadaye", "alicheka", "sheria", "kuweka", "kuongoza",
                "kujifunza", "angalau", "kuondoka", "kuongozwa", "kushoto",
                "miguu", "urefu", "chini ya", "basi", "hebu", "barua",
                "ngazi ya", "uongo", "maisha", "lile", "mwanga", "kama",
                "line", "hila", "orodha", "kidogo", "kuishi", "iko",
                "muda mrefu", "kuangalia", "waliopotea", "solder", "kubwa",
                "upendo", "chini", "mashine", "grub", "kuu", "kuu",
                "kufanya", "moja", "wengi", "ramani", "maandamano",
                "mafuta", "mechi", "vifaa", "matt", "inaweza", "labda",
                "mimi", "maana", "kupima", "nyama", "kukutana na",
                "melody", "wanachama", "wanaume", "chuma", "njia",
                "katikati", "nguvu pia", "mile", "maziwa", "milioni",
                "akili", "yangu", "dakika", "miss ya", "kisasa",
                "molekuli", "wakati", "fedha", "miezi", "mwezi", "zaidi",
                "asubuhi", "lazima", "mama", "mlima", "kinywa", "hoja",
                "harakati", "sana", "muziki", "lazima", "yangu", "jina",
                "taifa", "asili", "karibu", "muhimu", "haja", "kamwe",
                "mpya", "ijayo", "usiku", "hakuna", "kawaida", "kaskazini",
                "kaskazini", "pua", "dhiki", "kumbuka", "kitu", "taarifa",
                "noun", "sasa", "idadi ya", "numeral", "kitu",
                "kuchunguza", "bahari", "ya", "mbali", "ofisi",
                "mara nyingi", "oh", "mafuta", "miaka", "juu ya",
                "mara moja", "moja", "tu", "wazi", "kinyume", "au", "ili",
                "nyingine", "wetu", "nje", "nje", "juu ya", "kujitegemea",
                "oksijeni", "ukurasa", "rangi", "jozi", "karatasi", "aya",
                "Hifadhi ya", "sehemu", "hasa", "chama", "kupita",
                "siku za nyuma", "mfano", "kulipa", "watu", "na", "labda",
                "kipindi", "mtu", "maneno", "ilichukua", "picha",
                "kipande", "mahali", "tambarare", "ndege", "turubali",
                "mipango ya", "mimea", "kucheza", "tafadhali", "wingi",
                "shairi", "hatua", "pole", "maskini", "nafasi",
                "iwezekanavyo", "fedha", "nguvu", "mazoezi", "tayari",
                "marais", "pretty", "kuchapishwa", "pengine", "tatizo",
                "mchakato", "kuzalisha", "mboga", "mali", "Kutoa",
                "vunjwa", "kusukuma", "kuweka", "maswali", "haraka",
                "utulivu", "kabisa", "mbio", "radio", "mvua", "kukulia",
                "mbio", "badala", "kufikiwa", "kusoma", "tayari", "kweli",
                "sababu", "kupokea", "rekodi", "nyekundu", "kanda",
                "Kubaki", "kumbuka", "mara kwa mara", "ripoti",
                "kuwakilisha", "atapewa", "mabaki ya", "matokeo", "kurudi",
                "rhythm", "tajiri", "wapanda", "haki", "pete", "kupanda",
                "mto", "barabara", "mwamba", "limekwisha", "chumba",
                "mzizi", "kamba", "rose", "pande zote", "mstari",
                "utawala", "kukimbia", "salama", "Said", "meli", "mbegu",
                "mchanga", "kukaa", "kuokoa", "saw", "kusema", "wadogo",
                "shule", "sayansi", "wanasayansi", "alama", "bahari",
                "kiti cha", "pili", "sehemu", "ziwa", "mbegu", "kuonekana",
                "maziwa", "Kampuni", "kutuma", "scythes", "alimtuma",
                "hukumu", "tofauti", "kutumika", "kuweka", "makazi",
                "saba", "kadhaa", "atakuwa", "sura", "mkali", "yeye",
                "meli", "viatu", "duka", "short", "shoulderstand", "bega",
                "kelele", "show", "umeonyesha", "upande", "mbele",
                "ishara", "ishara", "kimya", "sawa", "rahisi", "tangu",
                "kuimba", "Mheshimiwa", "dada", "kukaa", "sita", "ukubwa",
                "ngozi", "anga", "usingizi", "polepole", "ndogo", "harufu",
                "alitabasamu", "theluji", "hivyo", "laini", "udongo",
                "askari", "ufumbuzi", "baadhi", "mtu", "kitu",
                "wakati mwingine", "lakini", "wimbo", "haraka", "sauti",
                "kusini", "kusini mwa", "nafasi", "kusema", "maalum",
                "kasi", "Spell", "kibiashara", "kuenea", "spring", "mraba",
                "kusimama", "nyota", "kuanza", "hali", "taarifa", "kukaa",
                "chuma", "hatua", "fimbo", "bado", "jiwe", "alisimama",
                "kuacha", "kuhifadhi", "hadithi", "moja kwa moja", "ajabu",
                "mkondo", "mitaani", "aliweka", "kamba", "nguvu",
                "wanafunzi", "utafiti", "somo", "vitu", "search", "ghafla",
                "suffix", "sukari", "alipendekeza", "Jumla", "buzzer",
                "jua", "usambazaji", "tuseme", "uhakika", "uso",
                "mshangao", "kuogelea", "silabi", "alama", "mfumo", "meza",
                "mkia", "kuchukua", "ulanga", "mrefu", "mwalimu", "timu",
                "kuwaambia", "joto", "th", "suala", "mtihani", "kuliko",
                "alifanya", "yao", "yao", "wao wenyewe", "kisha", "huko",
                "Thesis", "wao", "nene", "nyembamba", "kitu", "kufikiri",
                "tatu", "hii", "wale", "ingawa", "mawazo", "maelfu",
                "tatu", "kupitia", "Malthus", "amefungwa", "wakati",
                "vidogo", "kwa (ili)", "leo", "pamoja", "aliiambia",
                "tone", "pia", "alichukua", "Vyombo vya", "juu", "jumla",
                "kugusa", "kuelekea", "mji", "kufuatilia", "biashara",
                "treni", "usafiri", "mti", "pembetatu", "safari", "shida",
                "lori", "kweli", "kujaribu", "tube", "upande", "mbili",
                "daraja", "mjomba", "chini ya", "kusisitiza", "kuelewa",
                "kitengo cha", "mpaka", "up", "juu ya", "sisi", "kutumia",
                "Kwa kawaida", "bonde", "thamani", "mbalimbali", "verb",
                "sana", "maoni", "kijiji", "ziara ya", "sauti", "vowel",
                "kusubiri!", "kutembea", "ngome", "kutaka", "mara", "joto",
                "nini", "osha", "Washington", "hakuwa", "kuangalia",
                "maji", "mawimbi", "vinginevyo", "sisi", "kuvaa",
                "hali ya hewa", "wiki", "uzito", "vizuri", "tutaweza",
                "akaenda", "walikuwa", "magharibi", "magharibi", "nini",
                "magurudumu", "wakati", "ambapo", "kama", "ambayo",
                "wakati", "nyeupe", "ambao", "jumla", "ambao", "kwa nini",
                "mbalimbali", "mke", "pori", "anataka", "kushinda",
                "upepo", "dirisha", "mbawa", "majira ya baridi", "waya",
                "unataka", "na", "ndani ya", "bila", "mwanamke",
                "wanawake", "Wonderland", "si", "mbao", "neno", "kazi",
                "wafanyakazi", "dunia", "bila kufanya kwamba",
                "bila kufanya hivyo", "kuandika", "imeandikwa", "makosa",
                "aliandika", "yadi", "mwaka", "njano", "ndiyo", "lakini",
                "ninyi", "vijana", "yako", "mwenyewe"}};

}
