/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.pablo.naskfor;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int azuli=0x7f040000;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int SignUp=0x7f090003;
        public static final int action_settings=0x7f090008;
        public static final int dirForo=0x7f090004;
        public static final int dirUsers=0x7f090005;
        public static final int editText=0x7f090001;
        public static final int login=0x7f090002;
        public static final int pregunta=0x7f090006;
        public static final int user=0x7f090000;
        public static final int usrPreguntas=0x7f090007;
    }
    public static final class layout {
        public static final int activity_login=0x7f030000;
        public static final int activity_main=0x7f030001;
        public static final int activity_registro=0x7f030002;
    }
    public static final class menu {
        public static final int login=0x7f080000;
        public static final int main=0x7f080001;
        public static final int registro=0x7f080002;
    }
    public static final class string {
        public static final int SignUp=0x7f060000;
        public static final int action_settings=0x7f060001;
        public static final int app_name=0x7f060002;
        public static final int dirForo=0x7f060003;
        public static final int dirUsers=0x7f060004;
        public static final int hello_world=0x7f060005;
        public static final int newPregunta=0x7f060006;
        public static final int ownQuestions=0x7f060007;
        public static final int password=0x7f060008;
        public static final int registrar=0x7f060009;
        public static final int title_activity_main=0x7f06000a;
        public static final int title_activity_registro=0x7f06000b;
        public static final int user=0x7f06000c;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f070000;
    }
}
