package com.signnow.android.util;

public class IconFontMapping {

  public enum Icon {
		CURSOR(0, ""), CROSSHAIR(1, "⌖"), SCREENSHOT(2, "⌖"), SEARCH(3, "🔎"), ZOOM(4, ""), ZOOMIN(5, ""), ZOOMOUT(
				6, ""), VIEW(7, "👀"), EYE(8, "👀"), LOOK(9, "👀"), VISIBLE(10, "👀"), VISIBILITY(11, "👀"), ATTACH(
				12, "📎"), ATTACHMENT(13, "📎"), PAPERCLIP(14, "📎"), LINK(15, "🔗"), UNLINK(16, ""), MOVE(17, ""), EDIT(
				18, "✎"), WRITE(19, "✎"), PENCIL(20, "✎"), WRITINGDISABLED(21, ""), PENCILDISABLED(22, ""), ERASE(23,
				"✐"), ERASER(24, "✐"), COMPOSE(25, "📝"), LOCK(26, "🔒"), LOCKED(27, "🔒"), PRIVATE(28, "🔒"), SECURE(
				29, "🔒"), UNLOCK(30, "🔓"), UNLOCKED(31, "🔓"), PUBLIC(32, "🔓"), INSECURE(33, "🔓"), KEY(34, "🔑"), BACKSPACE(
				35, "⌫"), BAN(36, "🚫"), SMOKING(37, "🚬"), CIGARETTE(38, "🚬"), NOSMOKING(39, "🚭"), TRASH(40, ""), TRASHCAN(
				41, ""), TARGET(42, "◎"), TAG(43, ""), TAGS(44, ""), TAGGED(45, ""), KEYWORD(46, ""), KEYWORDS(47,
				""), BOOKMARK(48, "🔖"), FLAG(49, "⚑"), LIKE(50, "👍"), APPROVE(51, "👍"), THUMBSUP(52, "👍"), DISLIKE(
				53, "👎"), DISAPPROVE(54, "👎"), THUMBSDOWN(55, "👎"), HEART(56, "♥"), LOVE(57, "♥"), STAR(58, "⋆"), FAVORITE(
				59, "⋆"), SAMPLE(60, ""), EYEDROPPER(61, ""), CROP(62, ""), LAYERS(63, ""), LAYERGROUP(64, ""), PEN(
				65, "✒"), BEZIER(66, ""), VECTOR(67, ""), PIXELS(68, ""), RASTER(69, ""), PHONE(70, "📞"), CALL(71,
				"📞"), TELEPHONE(72, "📞"), PHONEDISABLED(73, ""), CALLDISABLED(74, ""), ENDCALL(75, ""), TELEPHONEDISABLED(
				76, ""), TOUCHTONEPHONE(77, "☏"), MAIL(78, "✉"), EMAIL(79, "✉"), ENVELOPE(80, "✉"), INBOX(81, "📥"), OUTBOX(
				82, "📤"), CHAT(83, "💬"), COMMENT(84, "💬"), TALK(85, "💬"), USER(86, "👤"), AVATAR(87, "👤"), MALEAVATAR(
				88, "👤"), MALEUSER(89, "👤"), USERS(90, "👥"), AVATARS(91, "👥"), USERGROUP(92, ""), BUSINESSUSER(93,
				""), MAN(94, "👨"), MALE(95, ""), MEN(96, ""), WOMAN(97, "👩"), FEMALE(98, ""), WOMEN(99, ""), RAISEDHAND(
				100, "✋"), HAND(101, ""), POINTUP(102, "👆"), POINTUPRIGHT(103, ""), POINTRIGHT(104, "👉"), POINTDOWNRIGHT(
				105, ""), POINTDOWN(106, "👇"), POINTDOWNLEFT(107, ""), POINTLEFT(108, "👈"), POINTUPLEFT(109, ""), CART(
				110, ""), SHOPPINGCART(111, ""), CREDITCARD(112, "💳"), CALCULATOR(113, ""), CALCULATE(114, ""), BARCHART(
				115, "📊"), PIECHART(116, ""), BOX(117, "📦"), PACKAGE(118, "📦"), HOME(119, "⌂"), HOUSE(120, "⌂"), GLOBE(
				121, "🌎"), EARTH(122, "🌎"), WORLD(123, "🌎"), NAVIGATE(124, ""), NAVIGATION(125, ""), LOCATE(126,
				""), COMPASS(127, ""), SIGNPOST(128, ""), DIRECTIONS(129, ""), LOCATION(130, ""), SAVE(131, "💾"), FLOPPYDISK(
				132, "💾"), DATABASE(133, ""), HARDDRIVE(134, ""), HDD(135, ""), MICROCHIP(136, ""), MUSIC(137, "♫"), MUSICNOTE(
				138, "♫"), AUDIO(139, "♫"), HEADPHONES(140, "🎧"), DISCDRIVE(141, ""), VOLUME(142, "🔈"), SOUND(143,
				"🔈"), SPEAKER(144, "🔈"), LOWVOLUME(145, "🔉"), MEDIUMVOLUME(146, ""), HIGHVOLUME(147, "🔊"), AIRPLAY(
				148, ""), CAMERA(149, "📷"), PICTURE(150, "🌄"), PICTURES(151, "🌄"), IMAGE(152, "🌄"), IMAGES(153,
				"🌄"), PHOTO(154, "🌄"), PHOTOS(155, "🌄"), PHOTOGRAPH(156, "🌄"), PHOTOGRAPHS(157, "🌄"), VIDEO(158,
				"📹"), VIDEOS(159, "📹"), VIDEOCAMERA(160, "📹"), WEBCAM(161, ""), FILM(162, ""), PLAYVIDEO(163, ""), VIDEOGAME(
				164, "🎮"), GAMING(165, "🎮"), PLAY(166, "▶"), PAUSE(167, ""), STOP(168, "■"), RECORD(169, "●"), REWIND(
				170, "⏪"), FASTFORWARD(171, "⏩"), SKIPBACK(172, "⏮"), SKIP(173, "⏭"), SKIPFORWARD(174, "⏭"), EJECT(175,
				"⏏"), REPEAT(176, "🔁"), REPLAY(177, "↺"), ROTATELEFT(178, "↺"), UNDO(179, "↺"), SHUFFLE(180, "🔀"), INDEX(
				181, ""), STORAGEBOX(182, ""), BOOK(183, "📕"), NOTEBOOK(184, "📓"), NEWSPAPER(185, "📰"), NEWS(186,
				"📰"), GRIDLINES(187, ""), ROWS(188, ""), COLUMNS(189, ""), THUMBNAILS(190, ""), MOUSE(191, ""), COMPUTERMOUSE(
				192, ""), USB(193, ""), DESKTOP(194, "💻"), COMPUTER(195, "💻"), DISPLAY(196, "💻"), MONITOR(197,
				"💻"), LAPTOP(198, ""), TABLET(199, ""), IPAD(200, ""), SMARTPHONE(201, ""), IPHONE(202, ""), MOBILE(
				203, ""), MOBILEPHONE(204, ""), CELL(205, "📱"), CELLPHONE(206, "📱"), BATTERY(207, "🔋"), FULLBATTERY(
				208, "🔋"), HIGHBATTERY(209, ""), MEDIUMBATTERY(210, ""), LOWBATTERY(211, ""), CHARGINGBATTERY(212,
				""), LIGHTBULB(213, "💡"), IDEA(214, "💡"), WASHER(215, ""), LAUNDRY(216, ""), DOWNLOADCLOUD(217,
				""), DOWNLOAD(218, ""), DOWNLOADBOX(219, ""), UPLOADCLOUD(220, ""), UPLOAD(221, ""), UPLOADBOX(
				222, ""), FORK(223, ""), MERGE(224, ""), REFRESH(225, "↻"), REDO(226, "↻"), ROTATERIGHT(227, "↻"), SYNC(
				228, ""), SYNCING(229, ""), LOADING(230, ""), FILE(231, "📄"), FILES(232, ""), DOCUMENTS(233, ""), PAGES(
				234, ""), ADDFILE(235, ""), REMOVEFILE(236, ""), CHECKFILE(237, ""), DELETEFILE(238, ""), EXE(239,
				""), ZIP(240, ""), DOC(241, ""), PDF(242, ""), JPG(243, ""), PNG(244, ""), MPTHREE(245, ""), RAR(
				246, ""), GIF(247, ""), FOLDER(248, "📁"), OPENFOLDER(249, "📂"), DOWNLOADFOLDER(250, ""), UPLOADFOLDER(
				251, ""), QUOTE(252, "“"), PULLQUOTE(253, "“"), UNQUOTE(254, "”"), PRINT(255, "⎙"), PRINTER(256, "⎙"), COPIER(
				257, ""), PHOTOCOPY(258, ""), FAX(259, "📠"), SCANNER(260, ""), SCAN(261, ""), PRINTREGISTRATION(
				262, ""), SHREDDER(263, ""), SHRED(264, ""), EXPAND(265, "⤢"), CONTRACT(266, ""), HELP(267, "❓"), QUESTION(
				268, "❓"), INFO(269, "ℹ"), INFORMATION(270, "ℹ"), ALERT(271, "⚠"), WARNING(272, "⚠"), CAUTION(273, "⛔"), EXIT(
				274, ""), LOGOUT(275, ""), SIGNOUT(276, ""), LOGIN(277, ""), ENTER(278, ""), SIGNIN(279, ""), SCALEUP(
				280, ""), SCALEDOWN(281, ""), PLUS(282, "+"), ADD(283, "+"), HYPHEN(284, "-"), MINUS(285, "-"), REMOVE(
				286, "-"), SUBTRACT(287, "-"), CHECK(288, "✓"), CHECKED(289, "✓"), CHECKMARK(290, "✓"), DELETE(291, "␡"), CLOSE(
				292, "␡"), NOTIFICATION(293, "🔔"), NOTIFICATIONS(294, "🔔"), BELL(295, "🔔"), NOTIFICATIONSDISABLED(
				296, "🔕"), NOTIFICATIONDISABLED(297, "🔕"), BELLDISABLED(298, "🔕"), CLOCK(299, "⏲"), TIME(300, "⏲"), STOPWATCH(
				301, "⏱"), TIMER(302, "⏱"), ALARM(303, "⏰"), ALARMCLOCK(304, "⏰"), EGG(305, ""), EGGS(306, ""), CHEESE(
				307, ""), CHICKENLEG(308, "🍗"), PIZZAPIE(309, ""), PIZZA(310, "🍕"), ZA(311, "🍕"), CHEESEPIZZA(312,
				""), FRENCHFRIES(313, "🍟"), APPLE(314, "🍏"), CARROT(315, ""), BROCCOLI(316, ""), CUCUMBER(317, ""), ORANGE(
				318, "🍊"), LEMON(319, "🍋"), ONION(320, ""), BELLPEPPER(321, ""), PEAS(322, ""), GRAPES(323, "🍇"), STRAWBERRY(
				324, "🍓"), BREAD(325, "🍞"), MUG(326, "☕"), COFFEE(327, "☕"), MUGS(328, ""), ESPRESSO(329, ""), MACCHIATO(
				330, ""), CAPPUCINO(331, ""), LATTE(332, ""), ICEDCOFFEE(333, ""), COFFEEBEAN(334, ""), COFFEEMILK(
				335, ""), COFFEEFOAM(336, ""), COFFEESUGAR(337, ""), SUGARPACKETS(338, ""), CAPSULE(339, ""), CAPSULERECYCLING(
				340, ""), INSERTCAPSULE(341, ""), TEA(342, "🍵"), TEABAG(343, ""), JUG(344, ""), MILK(345, ""), PITCHER(
				346, ""), KETTLE(347, ""), WINEGLASS(348, "🍷"), WINEGLASSSPARKLE(349, "🍷"), SUGAR(350, ""), OVEN(
				351, ""), STOVE(352, ""), VENT(353, ""), EXHAUST(354, ""), STEAM(355, "♨"), DISHWASHER(356, ""), TOASTER(
				357, ""), MICROWAVE(358, ""), ELECTRICKETTLE(359, ""), REFRIGERATOR(360, ""), FRIDGE(361, ""), FREEZER(
				362, ""), UTENSILS(363, "🍴"), COOKINGUTENSILS(364, ""), WHISK(365, ""), PIZZACUTTER(366, ""), MEASURINGCUP(
				367, ""), COLANDER(368, ""), EGGTIMER(369, ""), PLATTER(370, ""), PLATES(371, ""), STEAMPLATE(372,
				""), CUPS(373, ""), DRINKS(374, ""), STEAMGLASS(375, ""), POT(376, ""), STEAMPOT(377, ""), CHEF(
				378, ""), WEATHERVANE(379, ""), THERMOMETER(380, ""), TEMPERATURE(381, ""), THERMOMETERUP(382, ""), THERMOMETERDOWN(
				383, ""), DROP(384, "💧"), DROPLET(385, "💧"), SUNRISE(386, "🌅"), SUNSET(387, "🌇"), SUN(388, "☀"), SUNNY(
				389, "☀"), CLOUD(390, "☁"), CLOUDS(391, ""), CLOUDY(392, ""), PARTLYCLOUDY(393, "⛅"), PARTLYSUNNY(
				394, "⛅"), RAIN(395, "☔"), RAINY(396, "☔"), RAINHEAVY(397, ""), LIGHTNING(398, "☇"), THUNDERSTORM(399,
				"⛈"), UMBRELLA(400, "☂"), RAINUMBRELLA(401, ""), RAINBOW(402, "🌈"), RAINBOWCLOUDS(403, ""), FOG(404,
				""), WIND(405, ""), TORNADO(406, ""), SNOWFLAKE(407, "❄"), SNOWCRYSTAL(408, "❆"), LIGHTSNOW(409, ""), SNOW(
				410, ""), MEDIUMSNOW(411, ""), HEAVYSNOW(412, ""), HAIL(413, ""), CRESCENTMOON(414, "🌙"), WAXINGCRESCENTMOON(
				415, "🌒"), FIRSTQUARTERMOON(416, "🌓"), WAXINGGIBBOUSMOON(417, "🌔"), WANINGGIBBOUSMOON(418, "🌖"), LASTQUARTERMOON(
				419, "🌗"), WANINGCRESCENTMOON(420, "🌘"), FAN(421, ""), BIKE(422, "🚲"), BICYCLE(423, "🚲"), WHEELCHAIR(
				424, "♿"), WHEELCHAIRACCESSIBLE(425, "♿"), BRIEFCASE(426, "💼"), WORK(427, "💼"), HANGER(428, ""), COMB(
				429, ""), MEDICALCROSS(430, ""), UP(431, "⬆"), UPRIGHT(432, "⬈"), RIGHT(433, "➡"), FORWARD(434, "➡"), DOWNRIGHT(
				435, "⬊"), DOWN(436, "⬇"), DOWNLEFT(437, "⬋"), LEFT(438, "⬅"), BACK(439, "⬅"), UPLEFT(440, "⬉"), NAVIGATEUP(
				441, ""), NAVIGATERIGHT(442, "▻"), NEXT(443, "▻"), NAVIGATEDOWN(444, ""), NAVIGATELEFT(445, "◅"), PREVIOUS(
				446, "◅"), RETWEET(447, ""), SHARE(448, "");

		Icon(int ni) {
			nativeInt = ni;
			utf8String = null;
		}

		Icon(int ni, String f) {
			nativeInt = ni;
			utf8String = f;
		}

		final String utf8String;
		final int nativeInt;
	}

	private static final Icon[] sIconArray = new Icon[] { Icon.CURSOR, Icon.CROSSHAIR, Icon.SCREENSHOT, Icon.SEARCH,
			Icon.ZOOM, Icon.ZOOMIN, Icon.ZOOMOUT, Icon.VIEW, Icon.EYE, Icon.LOOK, Icon.VISIBLE, Icon.VISIBILITY,
			Icon.ATTACH, Icon.ATTACHMENT, Icon.PAPERCLIP, Icon.LINK, Icon.UNLINK, Icon.MOVE, Icon.EDIT, Icon.WRITE,
			Icon.PENCIL, Icon.WRITINGDISABLED, Icon.PENCILDISABLED, Icon.ERASE, Icon.ERASER, Icon.COMPOSE, Icon.LOCK,
			Icon.LOCKED, Icon.PRIVATE, Icon.SECURE, Icon.UNLOCK, Icon.UNLOCKED, Icon.PUBLIC, Icon.INSECURE, Icon.KEY,
			Icon.BACKSPACE, Icon.BAN, Icon.SMOKING, Icon.CIGARETTE, Icon.NOSMOKING, Icon.TRASH, Icon.TRASHCAN,
			Icon.TARGET, Icon.TAG, Icon.TAGS, Icon.TAGGED, Icon.KEYWORD, Icon.KEYWORDS, Icon.BOOKMARK, Icon.FLAG,
			Icon.LIKE, Icon.APPROVE, Icon.THUMBSUP, Icon.DISLIKE, Icon.DISAPPROVE, Icon.THUMBSDOWN, Icon.HEART,
			Icon.LOVE, Icon.STAR, Icon.FAVORITE, Icon.SAMPLE, Icon.EYEDROPPER, Icon.CROP, Icon.LAYERS, Icon.LAYERGROUP,
			Icon.PEN, Icon.BEZIER, Icon.VECTOR, Icon.PIXELS, Icon.RASTER, Icon.PHONE, Icon.CALL, Icon.TELEPHONE,
			Icon.PHONEDISABLED, Icon.CALLDISABLED, Icon.ENDCALL, Icon.TELEPHONEDISABLED, Icon.TOUCHTONEPHONE,
			Icon.MAIL, Icon.EMAIL, Icon.ENVELOPE, Icon.INBOX, Icon.OUTBOX, Icon.CHAT, Icon.COMMENT, Icon.TALK,
			Icon.USER, Icon.AVATAR, Icon.MALEAVATAR, Icon.MALEUSER, Icon.USERS, Icon.AVATARS, Icon.USERGROUP,
			Icon.BUSINESSUSER, Icon.MAN, Icon.MALE, Icon.MEN, Icon.WOMAN, Icon.FEMALE, Icon.WOMEN, Icon.RAISEDHAND,
			Icon.HAND, Icon.POINTUP, Icon.POINTUPRIGHT, Icon.POINTRIGHT, Icon.POINTDOWNRIGHT, Icon.POINTDOWN,
			Icon.POINTDOWNLEFT, Icon.POINTLEFT, Icon.POINTUPLEFT, Icon.CART, Icon.SHOPPINGCART, Icon.CREDITCARD,
			Icon.CALCULATOR, Icon.CALCULATE, Icon.BARCHART, Icon.PIECHART, Icon.BOX, Icon.PACKAGE, Icon.HOME,
			Icon.HOUSE, Icon.GLOBE, Icon.EARTH, Icon.WORLD, Icon.NAVIGATE, Icon.NAVIGATION, Icon.LOCATE, Icon.COMPASS,
			Icon.SIGNPOST, Icon.DIRECTIONS, Icon.LOCATION, Icon.SAVE, Icon.FLOPPYDISK, Icon.DATABASE, Icon.HARDDRIVE,
			Icon.HDD, Icon.MICROCHIP, Icon.MUSIC, Icon.MUSICNOTE, Icon.AUDIO, Icon.HEADPHONES, Icon.DISCDRIVE,
			Icon.VOLUME, Icon.SOUND, Icon.SPEAKER, Icon.LOWVOLUME, Icon.MEDIUMVOLUME, Icon.HIGHVOLUME, Icon.AIRPLAY,
			Icon.CAMERA, Icon.PICTURE, Icon.PICTURES, Icon.IMAGE, Icon.IMAGES, Icon.PHOTO, Icon.PHOTOS,
			Icon.PHOTOGRAPH, Icon.PHOTOGRAPHS, Icon.VIDEO, Icon.VIDEOS, Icon.VIDEOCAMERA, Icon.WEBCAM, Icon.FILM,
			Icon.PLAYVIDEO, Icon.VIDEOGAME, Icon.GAMING, Icon.PLAY, Icon.PAUSE, Icon.STOP, Icon.RECORD, Icon.REWIND,
			Icon.FASTFORWARD, Icon.SKIPBACK, Icon.SKIP, Icon.SKIPFORWARD, Icon.EJECT, Icon.REPEAT, Icon.REPLAY,
			Icon.ROTATELEFT, Icon.UNDO, Icon.SHUFFLE, Icon.INDEX, Icon.STORAGEBOX, Icon.BOOK, Icon.NOTEBOOK,
			Icon.NEWSPAPER, Icon.NEWS, Icon.GRIDLINES, Icon.ROWS, Icon.COLUMNS, Icon.THUMBNAILS, Icon.MOUSE,
			Icon.COMPUTERMOUSE, Icon.USB, Icon.DESKTOP, Icon.COMPUTER, Icon.DISPLAY, Icon.MONITOR, Icon.LAPTOP,
			Icon.TABLET, Icon.IPAD, Icon.SMARTPHONE, Icon.IPHONE, Icon.MOBILE, Icon.MOBILEPHONE, Icon.CELL,
			Icon.CELLPHONE, Icon.BATTERY, Icon.FULLBATTERY, Icon.HIGHBATTERY, Icon.MEDIUMBATTERY, Icon.LOWBATTERY,
			Icon.CHARGINGBATTERY, Icon.LIGHTBULB, Icon.IDEA, Icon.WASHER, Icon.LAUNDRY, Icon.DOWNLOADCLOUD,
			Icon.DOWNLOAD, Icon.DOWNLOADBOX, Icon.UPLOADCLOUD, Icon.UPLOAD, Icon.UPLOADBOX, Icon.FORK, Icon.MERGE,
			Icon.REFRESH, Icon.REDO, Icon.ROTATERIGHT, Icon.SYNC, Icon.SYNCING, Icon.LOADING, Icon.FILE, Icon.FILES,
			Icon.DOCUMENTS, Icon.PAGES, Icon.ADDFILE, Icon.REMOVEFILE, Icon.CHECKFILE, Icon.DELETEFILE, Icon.EXE,
			Icon.ZIP, Icon.DOC, Icon.PDF, Icon.JPG, Icon.PNG, Icon.MPTHREE, Icon.RAR, Icon.GIF, Icon.FOLDER,
			Icon.OPENFOLDER, Icon.DOWNLOADFOLDER, Icon.UPLOADFOLDER, Icon.QUOTE, Icon.PULLQUOTE, Icon.UNQUOTE,
			Icon.PRINT, Icon.PRINTER, Icon.COPIER, Icon.PHOTOCOPY, Icon.FAX, Icon.SCANNER, Icon.SCAN,
			Icon.PRINTREGISTRATION, Icon.SHREDDER, Icon.SHRED, Icon.EXPAND, Icon.CONTRACT, Icon.HELP, Icon.QUESTION,
			Icon.INFO, Icon.INFORMATION, Icon.ALERT, Icon.WARNING, Icon.CAUTION, Icon.EXIT, Icon.LOGOUT, Icon.SIGNOUT,
			Icon.LOGIN, Icon.ENTER, Icon.SIGNIN, Icon.SCALEUP, Icon.SCALEDOWN, Icon.PLUS, Icon.ADD, Icon.HYPHEN,
			Icon.MINUS, Icon.REMOVE, Icon.SUBTRACT, Icon.CHECK, Icon.CHECKED, Icon.CHECKMARK, Icon.DELETE, Icon.CLOSE,
			Icon.NOTIFICATION, Icon.NOTIFICATIONS, Icon.BELL, Icon.NOTIFICATIONSDISABLED, Icon.NOTIFICATIONDISABLED,
			Icon.BELLDISABLED, Icon.CLOCK, Icon.TIME, Icon.STOPWATCH, Icon.TIMER, Icon.ALARM, Icon.ALARMCLOCK,
			Icon.EGG, Icon.EGGS, Icon.CHEESE, Icon.CHICKENLEG, Icon.PIZZAPIE, Icon.PIZZA, Icon.ZA, Icon.CHEESEPIZZA,
			Icon.FRENCHFRIES, Icon.APPLE, Icon.CARROT, Icon.BROCCOLI, Icon.CUCUMBER, Icon.ORANGE, Icon.LEMON,
			Icon.ONION, Icon.BELLPEPPER, Icon.PEAS, Icon.GRAPES, Icon.STRAWBERRY, Icon.BREAD, Icon.MUG, Icon.COFFEE,
			Icon.MUGS, Icon.ESPRESSO, Icon.MACCHIATO, Icon.CAPPUCINO, Icon.LATTE, Icon.ICEDCOFFEE, Icon.COFFEEBEAN,
			Icon.COFFEEMILK, Icon.COFFEEFOAM, Icon.COFFEESUGAR, Icon.SUGARPACKETS, Icon.CAPSULE, Icon.CAPSULERECYCLING,
			Icon.INSERTCAPSULE, Icon.TEA, Icon.TEABAG, Icon.JUG, Icon.MILK, Icon.PITCHER, Icon.KETTLE, Icon.WINEGLASS,
			Icon.WINEGLASSSPARKLE, Icon.SUGAR, Icon.OVEN, Icon.STOVE, Icon.VENT, Icon.EXHAUST, Icon.STEAM,
			Icon.DISHWASHER, Icon.TOASTER, Icon.MICROWAVE, Icon.ELECTRICKETTLE, Icon.REFRIGERATOR, Icon.FRIDGE,
			Icon.FREEZER, Icon.UTENSILS, Icon.COOKINGUTENSILS, Icon.WHISK, Icon.PIZZACUTTER, Icon.MEASURINGCUP,
			Icon.COLANDER, Icon.EGGTIMER, Icon.PLATTER, Icon.PLATES, Icon.STEAMPLATE, Icon.CUPS, Icon.DRINKS,
			Icon.STEAMGLASS, Icon.POT, Icon.STEAMPOT, Icon.CHEF, Icon.WEATHERVANE, Icon.THERMOMETER, Icon.TEMPERATURE,
			Icon.THERMOMETERUP, Icon.THERMOMETERDOWN, Icon.DROP, Icon.DROPLET, Icon.SUNRISE, Icon.SUNSET, Icon.SUN,
			Icon.SUNNY, Icon.CLOUD, Icon.CLOUDS, Icon.CLOUDY, Icon.PARTLYCLOUDY, Icon.PARTLYSUNNY, Icon.RAIN,
			Icon.RAINY, Icon.RAINHEAVY, Icon.LIGHTNING, Icon.THUNDERSTORM, Icon.UMBRELLA, Icon.RAINUMBRELLA,
			Icon.RAINBOW, Icon.RAINBOWCLOUDS, Icon.FOG, Icon.WIND, Icon.TORNADO, Icon.SNOWFLAKE, Icon.SNOWCRYSTAL,
			Icon.LIGHTSNOW, Icon.SNOW, Icon.MEDIUMSNOW, Icon.HEAVYSNOW, Icon.HAIL, Icon.CRESCENTMOON,
			Icon.WAXINGCRESCENTMOON, Icon.FIRSTQUARTERMOON, Icon.WAXINGGIBBOUSMOON, Icon.WANINGGIBBOUSMOON,
			Icon.LASTQUARTERMOON, Icon.WANINGCRESCENTMOON, Icon.FAN, Icon.BIKE, Icon.BICYCLE, Icon.WHEELCHAIR,
			Icon.WHEELCHAIRACCESSIBLE, Icon.BRIEFCASE, Icon.WORK, Icon.HANGER, Icon.COMB, Icon.MEDICALCROSS, Icon.UP,
			Icon.UPRIGHT, Icon.RIGHT, Icon.FORWARD, Icon.DOWNRIGHT, Icon.DOWN, Icon.DOWNLEFT, Icon.LEFT, Icon.BACK,
			Icon.UPLEFT, Icon.NAVIGATEUP, Icon.NAVIGATERIGHT, Icon.NEXT, Icon.NAVIGATEDOWN, Icon.NAVIGATELEFT,
			Icon.PREVIOUS, Icon.RETWEET, Icon.SHARE };

	public static String getUtf8String(Icon icon) {
		return icon.utf8String;
	}

	public static Icon getIconAtIndex(int index) {
		return sIconArray[index];
	}

}
