/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.martin.isimplebutton;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int FrameLayout=0x7f08000c;
        public static final int GridLayout=0x7f080012;
        public static final int Linear=0x7f08000e;
        public static final int action_settings=0x7f080017;
        public static final int button=0x7f080002;
        public static final int button2=0x7f080003;
        public static final int button3=0x7f080014;
        public static final int button4=0x7f080015;
        public static final int buttonOnClick20=0x7f080000;
        public static final int checkBox=0x7f080004;
        public static final int imageButton=0x7f080007;
        public static final int imageView=0x7f080013;
        public static final int progressBar=0x7f080008;
        public static final int progressBar2=0x7f080009;
        public static final int radioButton=0x7f08000f;
        public static final int ratingBar=0x7f08000a;
        public static final int seekBar=0x7f08000b;
        public static final int seekBar2=0x7f080016;
        public static final int spinner=0x7f08000d;
        public static final int switch1=0x7f080005;
        public static final int textView=0x7f080001;
        public static final int textView2=0x7f080011;
        public static final int textView3=0x7f080010;
        public static final int toggleButton=0x7f080006;
    }
    public static final class layout {
        public static final int activity_my=0x7f030000;
    }
    public static final class menu {
        public static final int my=0x7f070000;
    }
    public static final class string {
        public static final int action_settings=0x7f050000;
        public static final int app_name=0x7f050001;
        public static final int hello_world=0x7f050002;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f060000;
    }
}
