/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.zyl.helloworld;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
        public static final int p1=0x7f020001;
        public static final int r1=0x7f020002;
        public static final int s1=0x7f020003;
        public static final int t1=0x7f020004;
        public static final int t2=0x7f020005;
        public static final int t3=0x7f020006;
        public static final int t4=0x7f020007;
        public static final int t5=0x7f020008;
        public static final int t6=0x7f020009;
    }
    public static final class id {
        public static final int action_settings=0x7f080003;
        public static final int btn_clickme=0x7f080000;
        public static final int iv1=0x7f080001;
        public static final int iv2=0x7f080002;
    }
    public static final class layout {
        public static final int activity_my=0x7f030000;
    }
    public static final class menu {
        public static final int my=0x7f070000;
    }
    public static final class string {
        public static final int action_settings=0x7f050000;
        public static final int app_name=0x7f050001;
        public static final int hello_world=0x7f050002;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f060000;
    }
}
