/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.projet.consulting.lttd.m3appli;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int Home=0x7f080001;
        public static final int articles=0x7f080002;
        public static final int clients=0x7f080003;
        public static final int listViewArticles=0x7f080000;
    }
    public static final class layout {
        public static final int activity_articles=0x7f030000;
        public static final int activity_clients=0x7f030001;
        public static final int activity_home=0x7f030002;
    }
    public static final class menu {
        public static final int articles=0x7f070000;
        public static final int clients=0x7f070001;
        public static final int home=0x7f070002;
    }
    public static final class string {
        public static final int action_articles=0x7f050000;
        public static final int action_clients=0x7f050001;
        public static final int action_home=0x7f050002;
        public static final int action_settings=0x7f050003;
        public static final int app_name=0x7f050004;
        public static final int hello_world=0x7f050005;
        public static final int title_activity_Home=0x7f050006;
        public static final int title_activity_articles=0x7f050007;
        public static final int title_activity_clients=0x7f050008;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f060000;
    }
}
