/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.paad.todolist.todolist;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int notepad_lines=0x7f040000;
        public static final int notepad_margin=0x7f040001;
        public static final int notepad_paper=0x7f040002;
        public static final int notepad_text=0x7f040003;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
        public static final int notepad_margin=0x7f050002;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int action_fragment=0x7f090005;
        public static final int action_settings=0x7f090004;
        public static final int list=0x7f090002;
        public static final int myEditText=0x7f090003;
        public static final int new_item_fragment=0x7f090000;
        public static final int to_do_lidt_fragment=0x7f090001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int my_list_fragment=0x7f030001;
        public static final int new_item_fragment=0x7f030002;
        public static final int todolist_item=0x7f030003;
    }
    public static final class menu {
        public static final int main=0x7f080000;
        public static final int my=0x7f080001;
    }
    public static final class string {
        public static final int action_fragment=0x7f060000;
        public static final int action_settings=0x7f060001;
        public static final int addItemContentDescription=0x7f060002;
        public static final int addItemHint=0x7f060003;
        public static final int app_name=0x7f060004;
        public static final int hello_world=0x7f060005;
        public static final int title_activity_my_fragment=0x7f060006;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f070000;
    }
}
